### PR TITLE
#594 Update `.table` styles to match Lexicon 2

### PR DESCRIPTION
**Pull request by pat270**

### CODE REVIEW

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Hey @pat270 `test-table-view-template.html` is not updated with this changes

**Comment by pat270** [comment]
@carloslancha `test-table-view-template.html` doesn't need to be updated because it's using \`.table-list\`? Do you mean the `h4` element?

**Comment by carloslancha** [comment]
Hey @pat270 yep, just to be consistent between examples

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Rebased and resent https://github.com/liferay/clay/pull/631

**Pull request closed without merging**
