### PR TITLE
Fixes #1171 - Implementation of loading indicator

### LINKED ISSUE #1171: Create loading-indicator component
While very simple markup, creating a loader component can simplify a lot building up UIs that require it.

Currently, this is supported by `clay-css` as:

```html
<span aria-hidden="true" class="loading-animation loading-animation-sm"></span>
<span aria-hidden="true" class="loading-animation"></span>
<span aria-hidden="true" class="loading-animation loading-animation-light"></span>
```

It would be great to have a clay abstraction on top as well.

### PR DESCRIPTION
**Pull request by bryceosterhaus**
https://github.com/liferay/clay/issues/1171

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
Anyone know how to get `npm run testSoy` to work locally? I am getting this error

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':runtime'.
> Could not download soy.jar (com.google.template:soy:2015-04-10)
   > Could not get resource 'https://cdn.lfrs.sl/repository.liferay.com/nexus/content/groups/public/com/google/template/soy/2015-04-10/soy-2015-04-10.jar'.
      > Premature end of Content-Length delimited message body (expected: 1596448; received: 244420
```

**Comment by julien** [comment]
Hey @bryceosterhaus ,
I haven't run into this error before but I've had similar issues while downloading dependencies with gradle, the URL you mentioned is accesible for me at this time ... but it looks like it wasn't when you tried to run the task ... maybe there was an issue with this cdn

**Comment by bryceosterhaus** [comment]
@julien yep that was the issue. I was able to download the dependencies today

**Comment by matuzalemsteles** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matuzalemsteles** [comment]
hey @bryceosterhaus, One thing before we merge this here, can you care to add this to the clayui.com documentation 🙂? Thank you very much.

**Comment by bryceosterhaus** [comment]
@matuzalemsteles just added soy and web component examples to clayui.com docs

**Comment by jbalsas** [comment]
Looking great, merging! 👍

**Pull request merged**
