### PR TITLE
feat(@clayui/form): add Select button in MultiSelect

### LINKED ISSUE #2366: MultiSelect does not have Select button
We should add the `Select` button to `ClayInputWithMultiSelect` or check if it is possible to compose.

Docs: https://docs.google.com/document/d/1cIx6RkWNbnho_fOSR__3Fp5alIBE_ObhO-jecfXlA9I/edit#heading=h.rbkugrj8xgm6

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Fixes #2366

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
hey @bryceosterhaus you are totally right about that, i thought something similar and i think it would be much better to see it happening. We just got into one issue, since our high-level ceiling is Lexicon, we should ship a component that can be customized only by API following the specifications. But I agree to deliver it as you suggested, we can treat it as a low-level to make accession easier.

**Comment by bryceosterhaus** [comment]
> since our high-level ceiling is Lexicon, we should ship a component that can be customized only by API following the specifications

Are you thinking we need to provide a _single_ component that meets lexicons specification via its props API? Maybe I am mistaken, but I thought our goal was to provide the _ability_ to build lexicon specifications with our low-level components and their API. For example, instead of having to deliver a single high-level component for MultiSelect that meets all specifications via its props, we would deliver the main blocks of components to compose that specification. Maybe it'd be helpful to have @jbalsas help clarify.

**Comment by matuzalemsteles** [comment]
> Are you thinking we need to provide a single component that meets lexicons specification via its props API? Maybe I am mistaken, but I thought our goal was to provide the ability to build lexicon specifications with our low-level components and their API. For example, instead of having to deliver a single high-level component for MultiSelect that meets all specifications via its props, we would deliver the main blocks of components to compose that specification. Maybe it'd be helpful to have @jbalsas help clarify.

I think we're messing things up a bit here, I think I lost our idea of ​​high-level a bit. I see high-level in another way (as I said in #2275).

I think if we deliver high-level as part of the component's Lexicon specifications, it may override our low-level, in fact I see we went the other way here. We deliver most of our high levels with the entire component specification (or near) and the low levels as small parts that help achieve the specification.

**Comment by bryceosterhaus** [comment]
> We deliver most of our high levels with the entire component specification (or near) and the low levels as small parts that help achieve the specification.

Yeah so what I am pushing for here is that we build low-level, which should be composable to meet lexicon specifications. Anything other than those low-level building blocks would be high-level. And instead of one high-level meeting every specification, we create one or more high-levels to meet a specific need that is used frequently, such as DropDownWithItems. It meets a basic need that is used frequently, but we don't try to adapt that high-level to meet _every_ need.

For this component specifically, I think the input portion of the component is technically a high-level component since it is comprised of other low-levels. However, the feedback and button portion should likely be composed together to create the full thing if needed. If we find that all three are used together really frequently, then we can create a high-level that meets that specific need. 

Does that make sense at all?

**Comment by carloslancha** [comment]
@bryceosterhaus if the approach you're following for the componentes is the composition It makes sense to do this in that way, I guess.

I'm working now on implementing the multiselect un portal and for now I'm kind if strugling to realize how to do some things that in 2.x was made vía API. Maybe adding examples for all the cases (or make them configurable with knots) in the storybooks would ve helpful.

**Comment by bryceosterhaus** [comment]
@carloslancha yeah thats a great idea. Would you mind linking to the one you are trying to implement? I can go through and try to add more demos to storybook for examples. Or even if there are a handful of components you want demos on, I can build out a handful, Im just not sure which examples to build out.

**Comment by matuzalemsteles** [comment]
> For this component specifically, I think the input portion of the component is technically a high-level component since it is comprised of other low-levels. However, the feedback and button portion should likely be composed together to create the full thing if needed. If we find that all three are used together really frequently, then we can create a high-level that meets that specific need.
>
> Does that make sense at all?

Yeah, that makes sense. I think we can change `ClayInputWithMultiSelect` to a low-level component.

I agree with @carloslancha, even though we have these low-level components we should add more demos to our storybook showing how you can reach Lexicon specifications using the low-level components by listing the use cases predicted by the documents.

**Comment by bryceosterhaus** [comment]
Technically I think `ClayInputWithMultiSelect` would still remain a high level component since it is high-level of input. But then we can also compose this high level with feedback and the button for the full range of multi-select specification. Does that sound about right to you? We may be saying the same thing in practicality but just using different language for it.

and im all for the extra demos. no reason we shouldn't add more.

**Comment by matuzalemsteles** [comment]
> Technically I think ClayInputWithMultiSelect would still remain a high level component since it is high-level of input.

Hmm yeah, I think I'm thinking that MultiSelect is a different component from `Input`... you're right about that.

> But then we can also compose this high level with feedback and the button for the full range of multi-select specification. Does that sound about right to you? 

Sounds good for me.

I think we can go with that and start revamp `ClayInputWithMultiSelect` we have a lot of changes to it in other PR's.

**Comment by bryceosterhaus** [comment]
@matuzalemsteles sounds good. Do you want to update that in this PR, or do you want me to go ahead and work on deconstructing it a bit? I'm fine either way.

**Comment by matuzalemsteles** [comment]
@bryceosterhaus I can close this PR, and you can work on deconstructing it, then we can add to the other changes we're talking about in the other open PR's.

**Comment by bryceosterhaus** [comment]
Sounds good. I'll add some examples for this exact case as well.

Thanks!

**Comment by matuzalemsteles** [comment]
Thanks @bryceosterhaus

**Pull request closed without merging**
