### PR TITLE
Fixed #2117 - Change draft styles

### LINKED ISSUE #2117: [next.clayui.com] the draft style looks like disabled
image

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
image

**Comment by matuzalemsteles** [comment]
Thanks for this @marcoscv-work, you can change the format of the commit message. Following https://github.com/liferay/clay/blob/master/CONTRIBUTING.md#git-commit-messages.

**Comment by matuzalemsteles** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matuzalemsteles** [comment]
hey @marcoscv-work I went ahead and changed. #2121

**Pull request closed without merging**
