### PR TITLE
fix(@clayui.com): add a sass function to fix table border-radius issue

### LINKED ISSUE #4722: @clayui/css: Table border radius has a blank space between the element and the border.
In table component, when we implement a border-radius in a child element, the parent with a border has a blank space between them. 
I'll be working on this fix among with @ethib137 and Eduardo Gusmão.

## Is there an example you can provide via codesandbox.com?
[Example](https://codesandbox.io/s/weathered-dream-rs30ip?file=/src/index.js)

### PR DESCRIPTION
**Pull request by ilzamcmed**
fixes #4722
In table component, when we implement a border-radius in a child element, the parent with a border has a blank space between them.
It was fixed by add a calculation to decrease the border-width from border-radius.

### CODE REVIEW

**Comment by pat270** [comment]
@ilzamcmed Thanks for the pr! I left some comments, let me know if you have any questions.

**Comment by ilzamcmed** [comment]
@pat270 Thank you! Can you tell me where are the comments? I couldn't find it here.

**Comment by pat270** [comment]
That's strange, it should look like this:
comments

**Comment by ilzamcmed** [comment]
I don't see this comments at all! Maybe something related to permissions? 
I'll work on those suggestions. Thank you!

**Comment by pat270** [comment]
@ilzamcmed it was my fault, I never submitted the review.

**Comment by pat270** [comment]
@ilzamcmed Thanks for the update. I made a couple changes.

I simplified the `clay-border-radius-inner` function, not every component has `border-width-x` and `border-width-y`. Also the CSS `min()` function doesn't have support in IE11, technically Clay CSS 3.x can be used in 7.2 which has limited support for IE11. I don't think anyone is doing this, but I'm not 100% sure about it.

I moved the `border-radius` properties to the `$c-table-list` Sass map and added docs for `clay-border-radius-inner`.

**Comment by matuzalemsteles** [comment]
Hey @pat270 @ilzamcmed does this look good to go ahead?

**Comment by ilzamcmed** [comment]
> Hey @pat270 @ilzamcmed does this look good to go ahead?
Everything is ok! Thanks guys!

**Pull request merged**
