### PR TITLE
chore: move the active development to the master branch

### PR DESCRIPTION
**Pull request by matuzalemsteles**
hey guys, this is a step so we can follow the pattern of branches in #2043. To conclude this we have to continue with the following changes.

- [ ] Rename `1.x-develop` to `1.x-stable`
- [ ] Rename `2.x-develop` to `2.x-stable`
- [ ] Rename `develop` to `stable`

To realize this change, we also have to start following the processes:

- Use `1.x` for maintenance and `1.x-stable` with the latest stable version of `1.x`.
- Use `2.x` for maintenance and `2.x-stable` with the latest stable version of `2.x`.
- Use `master` for active v3 development.
- Use `stable` with the last stable release of the master.

It will no longer be necessary to use the `next-release` label, as soon as the PR enters the main development branches they will be closed, to identify the launches check the [Releases](https://github.com/liferay/clay/releases) tab, to verify if the version has entered the Portal, we have to add the PR link that is taking care of it within Release note of the corresponding version.

🚨This PR has to enter first than the others that are in the queue and we must take care of changing the other PR's in the queue to point to the master and give rebase.

cc @bryceosterhaus @diegonvs

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
This change sounds good to me. Not sure if we want to wait a week and leave this open to alert anyone who might not see this immediately.

**Comment by matuzalemsteles** [comment]
Hm yeah, I'm going to merge this in the middle of next week so I want to have this process ready since we want to launch an alpha at the end of next week. So we can close a lot of issues we're "holding", we probably have more than 80 issues.

@pat270 @carloslancha

**Comment by wincent** [comment]
Just to have a high-level understanding of what's happening in this commit, is this the result of you merging "develop" into "master"?

Just one thing about "renaming" branches. While you can rename local branches with `git branch -m`, from GitHub's point of view there is no such thing as a rename — I think GitHub will see it at a new branch being created under the new name, and the old branch being deleted.

**Comment by matuzalemsteles** [comment]
> Just to have a high-level understanding of what's happening in this commit, is this the result of you merging "develop" into "master"?

Yeah

> Just one thing about "renaming" branches. While you can rename local branches with git branch -m, from GitHub's point of view there is no such thing as a rename — I think GitHub will see it at a new branch being created under the new name, and the old branch being deleted.

Yes, we will have to create new branches for this and delete the previous ones.

**Comment by matuzalemsteles** [comment]
hey guys, I'm going ahead and merging so we can keep working on this new flow. Next I'll be adding to `CONTRIBUTING.md`.

**Pull request merged**
