### PR TITLE
fix(@clayui/card): Use ClayButtonWithIcon instead of vanilla button in clay-card

### PR DESCRIPTION
**Pull request by markocikos**
This is a followup on https://github.com/liferay/clay/pull/3794, applying the same change to `ClayCardWithInfo` and `ClayCardWithUser`.

### CODE REVIEW

**Review by julien — APPROVED** [review]

**Review by matuzalemsteles — APPROVED** [review]
LGTM

**Comment by julien** [comment]
Hey @matuzalemsteles @bryceosterhaus do you know when the next clay update in DXP is scheduled?
Mostly asking because [this pr](https://github.com/liferay-frontend/liferay-portal/pull/495) is depending on it

**Comment by matuzalemsteles** [comment]
@julien I'm not sure but if this is a blocker, we can do it today.

**Comment by julien** [comment]
@matuzalemsteles if you can that would be great.

**Comment by matuzalemsteles** [comment]
@julien no problem, I will cut a new release today, @bryceosterhaus do you see any problems? Bryce if you want to do it too, feel free 🙂

**Comment by bryceosterhaus** [comment]
@matuzalemsteles I don't see any issues with cutting a release. I can release this afternoon if you don't get to it before then.

**Pull request merged**
