### PR TITLE
fix(@clayui/css): Atlas Table caption color is not accessible

### LINKED ISSUE #3806: Table caption is not correctly color contrasted and the visual order is not correct
## Add a `<caption>` to a Clay table

image

1) The contrast is not accessible:

image

2) The order is different in the code and in the render, it should be fixed:

image
but:
image

By CSS property:
image

Captions can be added from ckeditor:
https://issues.liferay.com/browse/LPS-123682

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-123682

fixes #3806

### CODE REVIEW

**Comment by wincent** [comment]
Assigning this to you @marcoscv-work to take a look; can you please verify this and merge it if it looks good to you?

cc @robertoDiaz

**Comment by robertoDiaz** [comment]
Thank you @wincent 👍

**Review by marcoscv-work — APPROVED** [review]

**Comment by antonio-ortega** [comment]
Hi guys,

We need to backport this fix to Clay 2.x and release a new version so we can have this fix in Liferay 7.2 and below. 

What's the procedure you follow to backport fixes in Clay? Shall I open a new issue? Shall I link it somehow to this one?

Thanks.

Regards.

**Comment by pat270** [comment]
@antonio-ortega I'll send a pr for 2.x today. You don't need to do anything.

**Pull request merged**
