### PR TITLE
chore: update lints

### PR DESCRIPTION
**Pull request by wincent**
Updates to eslint-config-liferay v19.0.2 which brings in some new rules:

- curly (enforces use of curlies around conditional blocks).
- liferay/import-extensions (prohibits superflous extensions in imports).
- liferay/array-is-array (enforces use of `Array.isArray` instead of `instanceof Array`).
- liferay/sort-import-destructures (yet another in the family of "sorting" rules).
- padding-line-between-statements (specifically, requiring a blank line before `return` statements, at Brian's request).
- react/forbid-foreign-prop-types (so that we can be sure that stripping propTypes in production builds is safe; obviously won't be relevant in this repo).

and produces [these new lint errors](https://gist.github.com/wincent/84bbd941eec684218acb21ad34fdb156).

All of those have autofixes, so I applied them.

I also removed some cruft from the config file (values that are not needed because they are the defaults).

Note that in testing this, I discovered that the new "liferay/sort-import-destructures" rule and the `@typescript-eslint/parser` parser were not playing nicely together. I first tried updating some of the related NPM packages (ESLint, the parser etc) but that didn't work (although it did require me to update one config value), so I then dug deeper and [tweaked the rule implementation to work with both](https://github.com/liferay/eslint-config-liferay/pull/153) the `@typescript-eslint/parser` and "espree" (ie. default) parsers:

### CODE REVIEW

**Comment by wincent** [comment]
Marking this as a draft @bryceosterhaus because it will conflict with https://github.com/liferay/clay/pull/2947 — once that one is in I will just re-run the autofixes on this branch and update it. Expect the tests to fail because of the stale snapshots ([fixed here](https://github.com/liferay/clay/pull/2948)).

**Comment by wincent** [comment]
Rebased on top of https://github.com/liferay/clay/pull/2947 (although I was wrong about it conflicting — it didn't) and taking out of draft status.

**Comment by wincent** [comment]
Two stalled jobs again:

- https://app.netlify.com/sites/storybook-clayui/deploys/5e54fcedb17a5e00081eb426

That seem to have completed just fine:

> Build time: 4m 12s. Total deploy time: 4m 12s
>
> Build started at 11:54:39 AM and ended at 11:58:51 AM. Learn more about build minutes.

**Comment by bryceosterhaus** [comment]
Tests are passing so that is good for me. The changes don't look like they would cause issue either.

Thanks for adding this!

**Pull request merged**
