### PR TITLE
Fixes https://github.com/liferay/clay/issues/1507

### LINKED ISSUE #1507: Clay Management Toolbar search field displays "undefined" instead of the placeholder text
Clay Management Toolbar search field displays "undefined" instead of the placeholder text.

Steps to reproduce:
1. Clone the clay repo: https://github.com/liferay/clay
2. Follow steps 1 through 6 in the setup section: https://github.com/liferay/clay/blob/master/README.md#setup
3. Go to http://localhost:4000/packages/clay-management-toolbar/demos/ and scroll down to the "With search results" heading.
4. In the blue bar that says "6-results-for-red" at the left, click "clear" at the right.

Expected result: the blue bar is cleared and the placeholder text ("search-for") is displayed in the search field.
Actual result: the blue bar is cleared but "undefined" is displayed in the search field.

This issue is the underlying cause of https://issues.liferay.com/browse/LPS-89868

### PR DESCRIPTION
**Pull request by jrao**
Fixes #1507 

Prevent 'undefined' from appearing in Clay management toolbar by using empty string for non-truthy values of 'searchValue'

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
hey @jrao, LGTM! Can you regenerate the snapshots jest and soy isomorphic tests? Thanks!

For jest tests:
- `yarn run jest -- -u`

For soy isomorphic tests:
- `cd packages/clay-isomorphic`
- `./gradlew :regenerateFixturesExpected`

**Comment by jrao** [comment]
Done! Is there any need to send a pr to master branch? (I reproduced and fixed the same issue on Clay master branch and have a branch ready to send.)

**Comment by matuzalemsteles** [comment]
hey @jrao thanks, it is not necessary, the branch master will be merged with the v3 that is now being worked on the `develop` branch.

**Comment by carloslancha** [comment]
Hey guys @matuzalemsteles @jrao , thanks for fixing this! Just a little request, please try to use self-explicative PR titles son we can know faster what's on each release during and after each release process. Thanks again!

**Pull request merged**
