### PR TITLE
feat(@clayui/date-picker): implements keyboard navigation to DatePicker

### LINKED ISSUE #5201: DatePicker component is not accessible
DatePicker component is not accessible following w3c recommendations https://www.w3.org/WAI/ARIA/apg/example-index/dialog-modal/datepicker-dialog.

Both the ARIA semantic part for the elements and the standard keyboard navigation part in the grid do not exist in the component.

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Fixes #5201

This PR finalizes the accessibility improvements for DatePicker by adding keyboard navigation and hotkeys as per w3c recommendations.

- [x] Keyboard navigation on the grid
- [x] Keyboard shortcuts on the grid
- [x] Focus via tab gets stuck inside Date Picker

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
I'm submitting the implementation of a new internal component is generic to handle overlay for Clay components and have consistent behavior. This makes code maintenance easier so that we don't have to replicate for all components, especially now that we're dealing with accessibility.

This component will also help to remove a lot of duplicate code in dialog and menu related components, it also develops a better mechanism for click out and suppression of non-assertive elements for the screen reader and lock focus within scope. This will benefit components like Modal, MultiSelect, Autocomplete, DropDown, DatePicker, ColorPicker and others.

I'm still going to send another commit that updates the DropDown component and consequently updates the other components that are using to go ahead with this PR and finish it. I will send the changes to Modal using another PR and another issue.

**Comment by matuzalemsteles** [comment]
Hey @marcoscv-work could you review the browsing behavior for the DatePicker?

**Comment by marcoscv-work** [comment]
I looks really great, button text are fantastic!
I think we could go ahead with this since is 1000 better than we already have and then provide improvements, thanks @matuzalemsteles 

We probably could improve the button of "Go to today" moving the focus to the day and probably the three icons could have titles since they are not something recognisable and need to be concrete:
image

So yeah, pretty sure that we would need "Previous month" "Go to today" and "Next month" titles.
Not something needs to be added right now if you need to release but good to add to the task-list.

Thanks @matuzalemsteles

**Comment by marcoscv-work** [comment]
I wanted to test it in Windows/JAWS but preview site is totally blocked in windows :-P

**Comment by matuzalemsteles** [comment]
> So yeah, pretty sure that we would need "Previous month" "Go to today" and "Next month" titles.
> Not something needs to be added right now if you need to release but good to add to the task-list.

Yes, that's really nice, I'll add to these elements it won't be a problem, we just had the `aria-label` label defined.

> I wanted to test it in Windows/JAWS but preview site is totally blocked in windows :-P

Oh no, really?! Is it not rendering or do you really see a blocking message? I can see that, maybe it's Netlify.

**Pull request merged**
