### PR TITLE
feat(link): remove 'unstable_' from ClayLinkContext

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
@matuzalemsteles I noticed that `next.clayui.com` seems to be pulling its dependencies from npm rather than our yarn workspace. Do you know if this is intended? I was hoping to update the docs and simultaneous make changes, but wasn't sure if that is the right workflow.

**Comment by matuzalemsteles** [comment]
@bryceosterhaus we also need to change the `package.json` versions of the `next.clayui.com` package so that it can get it from local. I will send a PR changing and you can rebase.

**Comment by matuzalemsteles** [comment]
Send #2471

**Comment by bryceosterhaus** [comment]
@matuzalemsteles seems to work now. Thanks! Let me know if you are okay with me merging this.

**Pull request merged**
