### PR TITLE
Implement Portals for clay-dropdown components

### PR DESCRIPTION
**Pull request by Robert-Frampton**
Updates metal dependencies to v2.16.1 and implements Portals for `ClayDropdown`.

### CODE REVIEW

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Robert-Frampton** [comment]
Hey @carloslancha, yeah I was thinking we'll need to abstract some of this. Creating a `ClayPortal` definitely makes sense.

For `getPortalElementNode_`, I like the idea, we would have to modify it a little for it to work with multiple components wanting to use the same element. For example, we'll still need to pass in the full selector so that subsequent components can leverage the element created by the first.

```
{call ClayPortal.render}
	{param content kind="html"}
		...
	{/param}
	{param portalElement: '#clay-dropdown-portal' /}
	{param ref: 'portal' /}
{/call}
```

So if it can't find the `#clay-dropdown-portal` element, `getPortalElementNode_` would strip the `#` and create it.

**Comment by Robert-Frampton** [comment]
@carloslancha, rebased against develop branch. Now using the new `ClayPortal` component.

**Comment by Robert-Frampton** [comment]
Not sure why these snapshots are failing. I don't get this locally :(

**Comment by Robert-Frampton** [comment]
@carloslancha I've published metal with the portal changes and updated this branch.

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
LGTM! 🎉

**Pull request merged**
