### PR TITLE
chore: run tests through github actions

### LINKED ISSUE #3190: Migrate travis.ci related jobs to github actions

### PR DESCRIPTION
**Pull request by bryceosterhaus**
fixes #3190

resent from https://github.com/liferay/clay/pull/3188

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
one note on this change is that I dont think coveralls can comment on this PR if its from forks due to github action tokens...

**Comment by wincent** [comment]
> Just depends how valuable we think the comment from coveralls is.

I personally don't find it all that valuable. Reducing coverage to a single number means, at best, people don't even notice it among all the other checks, and at worst, people paying too much attention to it and then mindlessly working to increase coverage in ways that raise costs (making brittle tests) without comensurate benefits (ie. wasting time trying to detect regressions in parts of the code that are unlikely to have a bug).

**Comment by jbalsas** [comment]
> I personally don't find it all that valuable. Reducing coverage to a single number means, at best, people don't even notice it among all the other checks, and at worst, people paying too much attention to it and then mindlessly working to increase coverage in ways that raise costs (making brittle tests) without comensurate benefits (ie. wasting time trying to detect regressions in parts of the code that are unlikely to have a bug).

micdrop

**Comment by bryceosterhaus** [comment]
👍👍I agree. Going to merge


I just noticed that coveralls commented on this.... no idea how that worked.

**Pull request merged**
