### PR TITLE
Issue 47 - Converts css block comments to sass comments

### PR DESCRIPTION
**Pull request by alexandervalencia**
Hey @Robert-Frampton,<br><br>Attached is the other part of the fix for [Issue #47](https://github.com/liferay/liferay-theme-tasks/issues/47) of liferay-theme-tasks.<br><br>Let me know if you have any questions.<br><br>Thanks!

### CODE REVIEW

**Comment by pat270** [comment]
We can't use Sass comments for the copyright. It won't be output in the compiled files.

**Comment by blzaugg** [comment]
Production output shouldn't need copyright comments, just source code.

**Comment by blzaugg** [comment]
This can be closed: https://github.com/liferay/liferay-theme-tasks/issues/47#issuecomment-329283702

**Comment by blzaugg** [comment]
@alexandervalencia, we'll need to find another approach, rather than just striping the comments,

**Pull request closed without merging**
