### PR TITLE
fix(clayui.com): fix multiple dates being active

### PR DESCRIPTION
**Pull request by kresimir-coko**
Fixes [Date and Time example format on Mobile device is inconsistent #2802
](https://github.com/liferay/clay/issues/2802)

The 2 dates being shown as active were being manually set in their respective classes, so I removed them.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
@kresimir-coko looks good! Before merging though, can you change the commit message to be `fix(clayui.com)`. Otherwise, our versioning tool will think that this change was a fix for the "@clayui/form" component

**Comment by kresimir-coko** [comment]
@bryceosterhaus done!

**Comment by bryceosterhaus** [comment]
Thanks! I updated the PR and merged it at https://github.com/liferay/clay/pull/3100

Instead of the committ message saying "@clayui.com" it should just be "clayui.com"

**Comment by kresimir-coko** [comment]
> Instead of the committ message saying "@clayui.com" it should just be "clayui.com"

Dang yo

**Pull request closed without merging**
