### PR TITLE
fix(clayui.com): Fixes error when trying to generate the ClayDropDownWithDrilldown component API Table

### PR DESCRIPTION
**Pull request by matuzalemsteles**
I had done some tests before and left some comments here #3721. What I did here was just update the react-docgen codebase to the latest one, we should try to see if we can keep up with @bryceosterhaus PR https://github.com/reactjs/react-docgen/pull/400 to just use the npm package.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
@matuzalemsteles I recently tried to see if we could avoid using our own fork, but still didn't work from their releases. I'm starting to think the project is just semi-dead at this point...

**Comment by matuzalemsteles** [comment]
> @matuzalemsteles I recently tried to see if we could avoid using our own fork, but still didn't work from their releases. I'm starting to think the project is just semi-dead at this point...

Yeah, I agree. Some days ago I was researching how we could build some better API Tables, with support for importing interfaces, links with more details to get a better experience. But I think we're going to have to create this manually, something like this https://react-spectrum.adobe.com/react-stately/useAsyncList.html#interface. I think it is worth the effort as it is a very important part of our documentation.

**Review by bryceosterhaus — APPROVED** [review]
LGTM! Looks like it generates the tables on the deploy preview

**Comment by wincent** [comment]
> I'm starting to think the project is just semi-dead at this point...

You could try mentioning `@danez` directly on it. The person who originally wrote the project left FB and is probably not super engaged with it right now.

**Pull request merged**
