### PR TITLE
Fixes #1564 - ClayCSS 2.x Aspect Ratio added utilities `.aspect-ratio-item-flush` and `.aspect-ratio-item-vertical-flush` to force images to fill remaining space

### LINKED ISSUE #1564: ClayCSS Aspect Ratio add a utility to make image 100% regardless of size
https://issues.liferay.com/browse/LPS-90203
https://issues.liferay.com/browse/LPS-90311

### PR DESCRIPTION
**Pull request by pat270**
@carloslancha @matuzalemsteles we will need to update Clay Card to accept different aspect ratio classes.

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matuzalemsteles** [comment]
Hey @pat270, the utility classes that we must allow in ClayCard are:

- `aspect-ratio-item-flush`
- `aspect-ratio-item-vertical-flush`

Should we allow the dev to change these classes or can we add them based on existing APIs programmatically?

This is what we currently do at ClayImageCard:
```soy
{let $aspectRatioClasses kind="text"}
    aspect-ratio-item-center-middle aspect-ratio-item-fluid
    {if not $imageSrc and $icon and $spritemap}
        {sp}card-type-asset-icon
    {/if}
{/let}
```

**Comment by pat270** [comment]
@matuzalemsteles I don't think we can add the classes programmatically. Some of the utility classes are developer preference on how the image should display.

**Comment by matuzalemsteles** [comment]
Thanks @pat270! I'll work on adding the API to customize. Does `aspect-ratio-3-to-2...` classes have an effect on ClayCard?

**Comment by pat270** [comment]
@matuzalemsteles It doesn't on Image, User, File Cards (card-type-asset) because Lexicon wanted them to be 16 to 9. Is there a new use case for different aspect ratios?

**Comment by matuzalemsteles** [comment]
Thanks for information @pat270, not just certifying 🙂

**Pull request merged**
