### PR TITLE
fix(@clayui/form): change the Dual List Box ordering side following the right side as the default behavior

### LINKED ISSUE #4312: Allow configuring the reordering of any side in DualListBox component
Currently the component implemented in React of DualListBox does not allow configuring the reordering, this is enabled by default only for the left side but some time ago the configuration was requested to modify the sides, for more context see #3985.

The purpose of this "issue" is to allow you to choose which side will have the reordering so it allows the team to choose depends on the context.

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Fixes #4312

See issue https://github.com/liferay/clay/issues/4312 to understand the context of the change and why we are following this as a fix rather than not changing this default behavior now.

### CODE REVIEW

**Review by julien — APPROVED** [review]
LGTM

**Comment by julien** [comment]
I might wait for @carloslancha to have a look, because I know he was interested, but I'm OK with this change.

**Comment by carloslancha** [comment]
LGTM. Just a small nit: [here](https://github.com/liferay/clay/pull/4322/files#diff-cf0c416b55a9a2267c0e760adfe730dde3c16a4722a3b36e9d9e6495335da080R154) we don't need to pass `spritemap` anymore.

**Comment by julien** [comment]
@carloslancha I'm not 100% sure, but I think we still need to pass it, because it's not wrapped in a `ClayIconSpriteContext`, meaning that if you don't pass this prop, you're likely to see a warning and no icons.

**Comment by carloslancha** [comment]
@julien we weren't passing it in the first `ClaySelectBox` before because `showArrows` were false. In `ClaySelectBox` the `spritemap` is only needed if `showArrows` is set to true.

It's not important and it's not harmful to pass it, just commented about it to follow the same behavior/pattern as before the change.

**Comment by julien** [comment]
@carloslancha you're right, my bad. I was looking at line 210, not the highlighted one (154), sometimes it's not easy to see everything in GitHub's UI

**Comment by julien** [comment]
All good, thanks @matuzalemsteles

**Pull request merged**
