### PR TITLE
fix(@clayui/css): Mixins `clay-label-size` and `clay-label-variant` convert to use new (easier to remember) Sass map keys. The old keys will still work and win over new keys.

### LINKED ISSUE #4069: @clayui/css: Convert mixins `clay-label-variant` and `clay-label-size` to use new Sass map key pattern
See #3987

### PR DESCRIPTION
**Pull request by pat270**
fixes #4069

### CODE REVIEW

**Review by matuzalemsteles — APPROVED** [review]
LGTM! Overall it looks good, @pat270 since we adopted a more nested `map`, can this add some extra cost on build time?

**Comment by pat270** [comment]
@matuzalemsteles Yes, I think I added around ~3s to build time. This is including `cadmin.css`. I'm comparing 2.x vs master branches using my smoke test site.

**Comment by marcoscv-work** [comment]
LGTM

**Comment by matuzalemsteles** [comment]
@pat270 don't worry, thanks, just something to keep an eye on

**Pull request merged**
