### PR TITLE
(#788) Atlas adjust font sizes

### PR DESCRIPTION
**Pull request by pat270**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @pat270, why use an `<h4>` for the modal dialog instead of the `<div>`, or what I assume would be better, an `<h1>`?

**Comment by pat270** [comment]
@jbalsas The document with font updates also had specific `h` tags and I forgot to undo this change. I asked them to remove it since `h` tags should depend on the structure of the document which we have no control over.

**Comment by jbalsas** [comment]
Sounds good, thanks @pat270! We might want to consider using a more semantic markup for this... 🤔

**Comment by pat270** [comment]
I'm open to suggestions, just not sure what we can do since the markup would depend on the content and how it's structured.

**Comment by jbalsas** [comment]
No rush, just thinking out loud :)

**Pull request merged**
