### PR TITLE
inputs need to be self closing

### PR DESCRIPTION
**Pull request by Robert-Frampton**

### CODE REVIEW

**Comment by jbalsas** [comment]
Just FYI, trying to udpate this in portal on the server side, these are the issues we're seeing:

```
Caused by: com.google.template.soy.error.SoyCompilationException: errors during Soy 
    ClayCardGrid.soy:168: error: Could not find a match for this HTML tag._				</ul>_      ^
    ClayCardGrid.soy:168: error: Could not find a match for this HTML tag._				</ul>_      ^
    ClayCheckbox.soy:91: error: 'input' tag is a void element and must not specify a close tag._		<input {$inputAttributes}></input>_                              ^
    ClayDropdownBase.soy:535: error: Could not find a match for this HTML tag._			</ul>_     ^
    ClayDropdownBase.soy:535: error: Could not find a match for this HTML tag._			</ul>_     ^
    ClayRadio.soy:84: error: 'input' tag is a void element and must not specify a close tag._		<input {$inputAttributes}></input>_                              ^__739_BUNDLE_CONTEXT_/META-INF/resources/metal-list/src/List.soy:5: error: Cannot mix SoyDoc params and header params in the same template. Please  migrate to the '{@param <name>: <type>}' syntax._ * @param? id_           ^__739_BUNDLE_CONTEXT_/META-INF/resources/metal-list/src/List.soy:6: error: Cannot mix SoyDoc params and header params in the same template. Please  migrate to the '{@param <name>: <type>}' syntax._ * @param? elementClasses_           ^__739_BUNDLE_CONTEXT_/META-INF/resources/metal-list/src/List.soy:7: error: Cannot mix SoyDoc params and header params in the same template. Please  migrate to the '{@param <name>: <type>}' syntax._ * @param? items_           ^_9 errors_ [Sanitized]
```

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Sent to https://github.com/liferay/clay/pull/533

**Pull request closed without merging**
