### PR TITLE
Fixes #1925 Update forms-hierarchy.md

### LINKED ISSUE #1925: ClayUI.com - link from Clay Forms Hierarchy page to Lexicon Form Hierarchy page is broken
On https://clayui.com/docs/components/forms/forms-hierarchy.html#clay-sidebar, the link labeled "Forms Hierarchy Pattern" points to a 404 - instead, it should point to https://liferay.design/lexicon/core-components/forms/forms-hierarchy/.

### PR DESCRIPTION
**Pull request by reinrl**
corrected link to Lexicon Forms Hierarchy page

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
hey @reinrl thanks for this, you can run these changes on top of the `2.x-develop` branch and follow with our branch 2.x contribution guide https://github.com/liferay/clay/blob/2.x-develop/CONTRIBUTING.md#git-commit-messages.

**Comment by reinrl** [comment]
I have added an issue, and updated the commit title to reference the issue ("Fixes #1925..."). Is this really a 2.x-specific issue?

 
 
  On Mon, Apr 29, 2019 at 12:44 PM, Matuzalém Teles<notifications@github.com> wrote:   
hey @reinrl thanks for this, you can run these changes on top of the 2.x-develop branch and follow with our branch 2.x contribution guide https://github.com/liferay/clay/blob/2.x-develop/CONTRIBUTING.md#git-commit-messages.

**Comment by matuzalemsteles** [comment]
@reinrl a branch 2.x-develop is with the most updated version of clayui.com, in branch develop and master, we will be adding the new site for version v3 that is being worked on in this PR #1525.

One more thing, you can rebase the 2.x-develop branch and also reference the issue no commit.
```
Fixes #1925 - Update forms-hierarchy.md
```

**Comment by matuzalemsteles** [comment]
Resent #1963

**Pull request closed without merging**
