### PR TITLE
LPD-35107 - Update sorting icons for Clay Table

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPD-35107

### CODE REVIEW

**Comment by ethib137** [comment]
@marcoscv-work or @drakonux would one of you mind reviewing the table sorting icons here to make sure it's correct: https://deploy-preview-5875--next-storybook-clayui.netlify.app/?path=/story/design-system-components-table--sorting

**Comment by drakonux** [comment]
Using your link @ethib137 with my PC, Edge 129.0.2792.79 (64 bits), at 100% zoom, one of the new ordering icons (`order-list-down`) seems cut. Zooming in, it looks perfect 🤷‍♂️ 

Could you check it?

screenshot-icon-cut

**Review by matuzalemsteles — APPROVED** [review]
LGTM! It seems to work very well for me, on mac and chrome. I at least don't see any problems with the icon at 100% zoom.

**Comment by ethib137** [comment]
@drakonux I don't see that issue on my computer either. If you want to create a bug ticket for it we can try to look into it, but I don't think it should block us merging this.

**Comment by ethib137** [comment]
@pat270 or @matuzalemsteles can you merge this if it looks okay?

**Comment by ethib137** [comment]
Thanks @matuzalemsteles when will we be cutting the next Clay release and putting this in Portal?

**Comment by matuzalemsteles** [comment]
@ethib137 We will cut it next Monday. If you need it sooner we can cut one today or tomorrow.

**Comment by ethib137** [comment]
Hey @matuzalemsteles if we could cut it sooner that would be very helpful. Thanks.

**Pull request merged**
