### PR TITLE
fix(@clayui/alert): fix inaccurate padding

### LINKED ISSUE #3231: ClayAlert space between icon and text
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?
https://codesandbox.io/s/jolly-visvesvaraya-hlxcg?file=/src/App.js

## What are the steps to reproduce?
Create a default `ClayAlert` in a React app (it doesn't matter if the alert variant is stripe)

## What is the expected result?
Lexicon define the space between the icon and the text as **8px**:
Frame 1

When adding a `ClayAlert` in React, the space is **17px**:
* 8px for element with classes `autofit-col inline-item-before`
* 4px for element with classes `autofit-col autofit-col-expand`
* 5px for `<strong class="lead"></strong>` element

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3  |
| React | 16.12.0 |
| Use in module | `analytics-reports-web` |
| Bug | https://issues.liferay.com/browse/LPS-113812 |

### PR DESCRIPTION
**Pull request by bryceosterhaus**
fixes #3231

### CODE REVIEW

**Comment by wincent** [comment]
(Tangential). Would be great to have a tool like https://happo.io/ (ie. a visual diff/regression tool) integrated here; would make it much easier to be confident that changes like this don't have any unanticipated side effects.

**Comment by jbalsas** [comment]
> (Tangential). Would be great to have a tool like https://happo.io/ (ie. a visual diff/regression tool) integrated here; would make it much easier to be confident that changes like this don't have any unanticipated side effects.

Big +1 from me

**Comment by bryceosterhaus** [comment]
@jbalsas will we be able to pay for it? Its taken ages to get this netlify account, I don't have great confidence in getting another paid service 😂

**Comment by pat270** [comment]
Markup LGTM

**Comment by dgarciasarai** [comment]
When is this going to be available in Liferay Portal? Thanks! :)

**Comment by wincent** [comment]
> When is this going to be available in Liferay Portal? Thanks! :)

I don't know the exact status, but we have [this ticket](https://issues.liferay.com/browse/IFI-1671) which has the relevant-sounding title of "Clay Bi-weekly release May 21st".

**Comment by jbalsas** [comment]
nottoday

(actually, maybe later today, but not for you)

**Pull request merged**
