### PR TITLE
Update the React Billboard package version

### PR DESCRIPTION
**Pull request by interaminense**
I'm sending this PR to update the React Billboard package version

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
hey @bryceosterhaus can you confirm if this will go to branch 2.x or will we just keep updates in 3.x?

**Comment by bryceosterhaus** [comment]
Since this is only for the react version, I would probably say to just update it in 3.x. I don't think `clay-charts-react` was ever actually released for 2.x, we had set it as a private module and didn't intend to release until 3.x. See this pr, https://github.com/liferay/clay/pull/1306

**Comment by bryceosterhaus** [comment]
@interaminense I'm guessing this is for use in AC project right? Since we were waiting for v3.x of clay, I told Kien to go ahead and just copy over clay-charts-react to the AC project itself, if you need the new version you should be able to update in that project. Check out https://github.com/liferay/com-liferay-osb-faro-private/tree/7.1.x-private/osb-faro-web/src/main/js/clay-charts-react and https://github.com/liferay/com-liferay-osb-faro-private/blob/7.1.x-private/osb-faro-web/package.json#L92

**Comment by interaminense** [comment]
Hi @bryceosterhaus, I've already updated the React Billboard version in the AC repository, I'm sending this PR to recommend that clay should update it in the package as well.

Let me know if you want me to send this PR to Clay's 3.x branch.

Thanks, guys.

**Comment by bryceosterhaus** [comment]
@interaminense yeah go ahead and update the clay-charts package on the `develop` branch

**Comment by matuzalemsteles** [comment]
hey @interaminense, I'm closing let me know if you have time to send the update to the `develop` branch if not, I can do this.

**Pull request closed without merging**
