### PR TITLE
chore(release): publish v2.21.5

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by wincent** [comment]
I have no idea how the v2 release process works (@carloslancha holds the world record for v2 releases, I believe), but I do see duped versions in the lockfile.

**Comment by julien** [comment]
@wincent I'll talk with @carloslancha , I'm following https://github.com/liferay/clay/blob/2.x/CONTRIBUTING.md#release-process

**Comment by julien** [comment]
@wincent so running `yarn why billboard.js` outputs this 

```
yarn why v1.22.4
[1/4] Why do we have the module "billboard.js"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "billboard.js@1.12.11"
info Reasons this module exists
   - "_project_#clay-charts" depends on it
   - Hoisted from "_project_#clay-charts#billboard.js"
info Disk size without dependencies: "11.23MB"
info Disk size with unique dependencies: "13.9MB"
info Disk size with transitive dependencies: "15.74MB"
info Number of shared dependencies: 24
=> Found "react-billboardjs#billboard.js@1.6.2"
info This module exists because "_project_#clay-charts-react#react-billboardjs" depends on it.
info Disk size without dependencies: "4.29MB"
info Disk size with unique dependencies: "5.36MB"
info Disk size with transitive dependencies: "12.02MB"
info Number of shared dependencies: 36
Done in 1.14s.
```

I'm going to speak with @carloslancha just to make sure the release process for v2 is up to date

**Comment by wincent** [comment]
[Given the version range](https://github.com/planttheidea/react-billboardjs/blob/2540ac528e41cddf987d5955af3d11c8cbf575d4/package.json#L31) in react-billboard, we might be able to avoid the unnecessary duplication there, either/or:

- Updating that dep; and/or:
- Doing an `npx yarn-deduplicate yarn.lock`

**Comment by carloslancha** [comment]
> I have no idea how the v2 release process works (@carloslancha holds the world record for v2 releases, I believe), but I do see duped versions in the lockfile.

Release process changed since that times so I probably don't have all the context now, but this looks good (plus the duplicated stuff in `yarn.lock`

**Comment by julien** [comment]
Re-submitted here https://github.com/liferay/clay/pull/3671

**Pull request closed without merging**
