### PR TITLE
fix(@clayui/css): Cards `card-interactive-primary` Chrome 81/83 hover transition artifact

### LINKED ISSUE #3233: Chrome 81 Card Interactive Primary Flicker
Hover state on `card-interactive-primary` bugs out on Chrome 81. We need to change the transition to anything other than `ease-in-out` or `ease-in`. Original report: https://github.com/liferay/clay/pull/3204#discussion_r426512328

82200524-67932380-98ff-11ea-935d-7b515d9765ab

Also changing `box-shadow: none` to `box-shadow: 0 0 4px 0 rgba(0,0,0,0)` or `box-shadow: 0 4px 0 0 rgba(0,0,0,0)` seems to fix the issue.

### PR DESCRIPTION
**Pull request by pat270**
fixes #3233

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
This is great @pat270 :D

image

**Comment by jbalsas** [comment]
That `atlas.css` is 3 times the size of `bootstrap.css` gives me the chills... should have room for improvement there!

**Comment by wincent** [comment]
> That `atlas.css` is 3 times the size of `bootstrap.css` gives me the chills... should have room for improvement there!

I agree. I think we could be at least 10x the size of `bootstrap.css`.

😂

**Comment by marcoscv-work** [comment]
@jbalsas we are 3x better at least! and we could be 10x @wincent :-P

I think having those data to compare each time we compile the CSS can help to be focused on weight

**Comment by pat270** [comment]
Thanks @marcoscv-work! @jbalsas trying to drop it down, but hard to do without completely removing components.

**Comment by jbalsas** [comment]
That's okay, @pat270, we're doing just fine, let's keep pushing :)

**Pull request merged**
