### PR TITLE
Fixes #1664 Accordion/collapsible sm size

### LINKED ISSUE #1664: Accordion/collapsible sm size
image

Actually it will be used only in sidebar

Based on:
https://issues.liferay.com/browse/LEXI-537

### PR DESCRIPTION
**Pull request by pat270**

### CODE REVIEW

**Comment by pat270** [comment]
@marcoscv-work do we have `.panel-unstyled` in 7.x? If so I probably need to redo the `panel-unstyled` in this pull.

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Confirmed by Lexicon team, we do not longer need .panel-unstyled

**Comment by marcoscv-work** [comment]
@pat270 can you review the conflict and merge? thanks!

**Comment by pat270** [comment]
@marcoscv-work fixed conflict

**Pull request merged**
