### PR TITLE
Create `data` API to replace `columns` in Charts Fixes #526

### LINKED ISSUE #526: Create `data` API to replace `columns` in Charts
The `columns` API is very framework/implementation specific and leaves very little room to the imagination.

I propose we:
- Deprecate `columns` in all charts as an API
- Add `data` as an API that would be passed down to the underlying `columns` billboard attribute when appropriate and that could receive:
    - An `object` with the data
    - A `string` with a URI endpoint to fetch the data
    - A method that returns a promise that gets resolved with the data

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
I'm wondering if we couldn't get rid of the [`columns` property in `ChartBase`](https://github.com/julien/clay/blob/chart-new-features/packages/clay-charts/src/ChartBase.js#L766-L783) and only keep `data` instead of maintaining the two. /cc @Robert-Frampton @jbalsas

**Comment by julien** [comment]
Hey @brunobasto and @bryceosterhaus,

Would it be an issue for you if we replaced `columns` with `data` ?

Thanks!

**Comment by julien** [comment]
Hey guys,

I'm closing this pull request since we're also going to replace trailing underscores with leading underscores (see [#574](https://github.com/liferay/clay/pull/574)), but I still need your precious feedback when you can so feel free to comment even though this one is closed.

Thanks!

**Comment by brunobasto** [comment]
Hey @julien, I think it should be fine for me.

**Comment by julien** [comment]
Ok, Thanks @brunobasto

**Pull request closed without merging**
