### PR TITLE
fix(@clayui/css): SVG Icons updates `align-image-center`, `align-image-left`, and `align-image-right` with rounded borders

### PR DESCRIPTION
**Pull request by wincent**
Rebase of https://github.com/liferay/clay/pull/3440 — just putting this up as a draft so that we can compare the conflict resolution.

Fixes https://github.com/liferay/clay/issue/3432

### CODE REVIEW

**Comment by wincent** [comment]
[Here is the diff](https://github.com/liferay/clay/compare/da113090f4f6c779dd094fe8e6dc7068154fc8a7..2a228c535b62cbe24dbf1310d1c1d65dc21f5dfb) between https://github.com/liferay/clay/pull/3440/commits/da113090f4f6c779dd094fe8e6dc7068154fc8a7 (current HEAD of https://github.com/liferay/clay/pull/3440) and https://github.com/liferay/clay/pull/3458/commits/2a228c535b62cbe24dbf1310d1c1d65dc21f5dfb (current HEAD of this PR).

- This one maintains alpha ordering in `clayui.com/svg-icons.js`.
- #3440 seems to introduce duplicate `align-image-left` entry in packages/clay-css/src/scss/functions/_global-functions.scss.

**Comment by jbalsas** [comment]
Yeah, this LGTM, the other seemed to have some weird side-effects

**Comment by jbalsas** [comment]
This got me thinking... is `packages/clay-css/src/scss/functions/_global-functions.scss` manual or auto-generated?

**Comment by wincent** [comment]
> This got me thinking... is `packages/clay-css/src/scss/functions/_global-functions.scss` manual or auto-generated?

I have no idea, but I write machine code directly in binary, because running assembly through a compiler strikes me as an unnecessarily high-level of abstraction. @pat270 or @marcoscv-work (etc) will know.

**Comment by wincent** [comment]
Ok, just tried:

1. Edit `_global-functions.scss`
2. See `git diff` shows the change.
3. Run `yarn run gulp` in `packages/clay-css`.
4. See `git diff` shows now changes (ie. exactly matches the output in this PR).

For me, the takeaways here are that:

- We shouldn't be resolving merge conflicts in the GitHub UI.
- Autogenerated files are cool because they can eliminate human error.
- We should put something more obvious inside autogenerated files so that people realize they shouldn't be editing them.

**Comment by wincent** [comment]
Anyway, going to merge this to get it out of the queue.

**Comment by marcoscv-work** [comment]
LGTM, I've tried the same and the autogenerated file is correct, I will avoid the GitHub UI next time

**Comment by pat270** [comment]
Only the icons part of `_global-functions.scss` is autogenerated. https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/functions/_global-functions.scss#L322

**Comment by jbalsas** [comment]
> Only the icons part of _global-functions.scss is autogenerated. https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/functions/_global-functions.scss#L322

Maybe that should be split elsewhere, then?

It's easier to track autogenerated things independently so one knows what can be edited manually and what shouldn't. It also helps in cases like this where simply re-running the generation scripts is enough to get back to a consistent state.

**Comment by wincent** [comment]
> Maybe that should be split elsewhere, then?
> 
> It's easier to track autogenerated things independently so one knows what can be edited manually and what shouldn't. It also helps in cases like this where simply re-running the generation scripts is enough to get back to a consistent state.

In other projects I've gone as far as sticking such files in a directory like `__generated__/foo.bar`.

**Comment by pat270** [comment]
Works for me, created https://github.com/liferay/clay/issues/3469. We can continue discussion there.

**Pull request merged**
