### PR TITLE
Fixes #1463 - Add support for icons in clay cards stickers

### LINKED ISSUE #1463: Add support for stickers with icons in Clay Cards

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
@pat270 after adding support for icons in user cards we have following issue:

image

Icon is not correctly align inside the sticker. Could you please take a look? Thanks!

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
> @pat270 after adding support for icons in user cards we have following issue:
> 
> image
> 
> Icon is not correctly aligned inside the sticker. Could you please take a look? Thanks!

Hey @carloslancha you only need to change the span with class "inline-item" for "sticker-overlay"

image

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/carloslancha/clay/pull/6. [See changes here.](https://github.com/liferay/clay/compare/96c5bddbc~1...96c5bddbc) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
