### PR TITLE
fix(@clayui.css): LPD-44793 toggle-switch-sm label text breaks to new…

### PR DESCRIPTION
**Pull request by pat270**
… line too early

https://liferay.atlassian.net/browse/LPD-44793
toggle-switch-sm

### CODE REVIEW

**Comment by pat270** [comment]
@SelenaAungst  idk why I can't assign you as a reviewer.

**Comment by SelenaAungst** [comment]
@pat270 I don't think I have access to the liferay/clay repo so I can't be added as a reviewer, I'll see if I can request it.

**Comment by SelenaAungst** [comment]
LGTM!

**Review by ilzamcmed — APPROVED** [review]
LGTM!
Thanks @pat270!

**Review by matuzalemsteles — APPROVED** [review]
LGTM

**Pull request merged**
