### PR TITLE
Fixes #1265 - Update markup for icon left and right in the ClayDropdown

### LINKED ISSUE #1265: Update ClayDropdown Markup
We need to update the ClayDropdown markups with the recent changes in #1245.

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Hey @matuzalemsteles this changes were intended to support the render of items with icons in both sides at a time.

We need to add to the `itemsIconAlignment` param the option `both` and if `both` is passed render `dropdown-menu-indicator-start` and `dropdown-menu-indicator-end` in `.sections` template div classes.

We also need to be able to receive each item alignment inside the item object (so one can be left aligned and other right aligned).

Anyway, @pat270 @marcoscv is there any way to have the markup so we don't need to place the `dropdown-menu-indicator-start` and/or `dropdown-menu-indicator-end`? Right now we're forcing the developers to know if any item of the list has an icon in order to specify the generic `iconsAlignment` when maybe this should be specified only by element.

**Comment by matuzalemsteles** [comment]
hey @carloslancha, Makes sense, I thought we would not support this in ClayDropdown, just that it was a "Satellite".

**Comment by matuzalemsteles** [comment]
hey @carloslancha, Since we will continue with this, we will have to modify the API so that it can accept different icons on the ends, I believe this will cause a breaking change. Do you have any idea how we can get around this? if necessary.

**Comment by carloslancha** [comment]
Hey @matuzalemsteles sorry, I'm a little bussy this week preparing a workshop and on thursday I'll be on vacation. Do you mind to wait 'till Tuesday so I can take a look then? Thx!

**Comment by matuzalemsteles** [comment]
Sure. No problems. I'll try to take a look at this too and if have something I'll share it here.

**Comment by matuzalemsteles** [comment]
I will close this PR and send another with a proposal.

**Pull request closed without merging**
