### PR TITLE
fix(@clayui/css): Atlas Theme change body background-color to #fff to…

### LINKED ISSUE #3863: @clayui/css Atlas Theme change body element background-color to #fff
Portal Classic and Admin themes have body `background-color: #fff`. Not sure when it changed, but we should change to match.

### PR DESCRIPTION
**Pull request by pat270**
… match Classic and Admin themes

fixes #3863

### CODE REVIEW

**Comment by jbalsas** [comment]
Looks good, this means we can remove the overwrite in DXP when we integrate this, right?

/cc @bryceosterhaus !

**Comment by pat270** [comment]
@jbalsas Yes, what is the best way to get this done? Create an issue when the next version of Clay is released and merged?

**Comment by bryceosterhaus** [comment]
@pat270 I was planning to cut a release tomorrow. Do I need to overwrite something in DXP when I update the versions?

**Comment by pat270** [comment]
@bryceosterhaus I can send you a pr with the changes, you can cherry-pick the commits or something like that.

**Comment by bryceosterhaus** [comment]
@pat270 perfect!

**Pull request merged**
