### PR TITLE
fix(@clayui/css): Atlas Menubar and Pagination update active and hover state to improve contrast

### LINKED ISSUE #5490: Active/Hover state in Vertical Nav and Pagination
The current style of the vertical navigation has some contrast problems for the hover and active states, this document aims to fix those problems and provide a clear way to see which navigation item is selected/hover.

_Note_: The new style has to be the replacement for the old one being applied to DXP, to correct it in DXP and propagate the change.

**Vertical Nav changes:**
Mouse Hover / Active state:

Focus in active and focus in inactive example:

**Pagination**:
Active/hover state examples:

Full documentation:
https://liferay.atlassian.net/wiki/spaces/ENGLEXICON/pages/2337374209/Vertical+Nav+-+Review+for+accessibility

Related to LPS:
https://issues.liferay.com/browse/LPS-168530

/cc @emiliano-cicero

### PR DESCRIPTION
**Pull request by pat270**
fixes #5490

### CODE REVIEW

**Review by matuzalemsteles — APPROVED** [review]
LGTM! @pat270 just a detail that I noticed the weight of the font seems to be bigger when it is in the active state, maybe we have to increase it.

**Comment by pat270** [comment]
@matuzalemsteles It looks like the `font-weight` is larger for me. What are you seeing?

vert-nav

**Comment by pat270** [comment]
@matuzalemsteles Did you mean hover state? I just noticed it's bolder in the screen shot.

**Comment by matuzalemsteles** [comment]
@pat270 I was looking at the Pagination use case it still looks like it's font weight is less when it's in active state the Vertical Nav looks good.

**Comment by pat270** [comment]
@matuzalemsteles Thanks for pointing that out, should be good to go now. I adjusted some other things like content slightly shifting on hover due to bolder font weight.

**Pull request merged**
