### PR TITLE
docs(clayui.com): Blog post Slimming Down Clay

### LINKED ISSUE #4636: clayui.com: Write a blog post about how to reduce clay's footprint for guest requests in a Liferay Theme
> Is there any way I could somehow load just what's needed for guest requests (e.g. css variables and some utility classes) and just load the rest for logged in requests (where I assume the bulk of it is needed?)

We should write something about how to do this. This was for DXP 7.3.

### PR DESCRIPTION
**Pull request by pat270**
Looking for some feedback on this before we merge it.

fixes #4636

### CODE REVIEW

**Comment by ethib137** [comment]
Hey @pat270 I think this is great! Not only does it provide a succinct way to reduce the size of Clay on first load but it also is a great overview of some of Clay's architecture. This is really helpful. Thanks for taking the time to put this together.

**Review by julien — APPROVED** [review]

**Comment by julien** [comment]
@pat270 I think it's a good idea to document this, feel free to add more information if needed

**Review by matuzalemsteles — APPROVED** [review]
Looks good to me, Also, feel free to merge or add more stuff.

**Comment by pat270** [comment]
What kind of more stuff should I add? Any ideas or info that you guys think are missing?

**Comment by marcoscv-work** [comment]
Great!!!!

**Comment by marcoscv-work** [comment]
> What kind of more stuff should I add? Any ideas or info that you guys think are missing?

I think ias pretty clear and examples are directly applied to portal so I think better short-well-explained-post in this case :-D

**Comment by matuzalemsteles** [comment]
> What kind of more stuff should I add? Any ideas or info that you guys think are missing?

I don't have many ideas, but something I had said in the thread would be interesting about the strategy of creating a critical CSS to be loaded first and the rest of the CSS to be loaded later but to put that we would have to test it first and see if we have great advantages, I imagine so, we can create other blogs about it too.

**Comment by pat270** [comment]
Thanks everyone, I'm going to merge this and we can edit / new post it later if something comes up.

**Pull request merged**
