### PR TITLE
chore(next.clayui.com): change the look of the documentation page

### LINKED ISSUE #2337: Change the look of the next.clayui.com documentation page
We need to make visual adjustments on the documentation screen in order to organize a little, we will keep the same structure.

Something similar to this:
Screen Shot 2019-08-24 at 13 54 20

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Fixes #2337

As we talked via Slack, I am maintaining the same structure but changing the look and adding the top bar but discreetly 🙂.

cc @eduardoallegrini @marcoscv-work

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
Just started reviewing :)

**Comment by eduardoallegrini** [comment]
I like the design! There are a few minor issues that I'd like to resolve before merge
links focus
image
Minor space adjustment
image
responsive changes
image
image
image

**Comment by matuzalemsteles** [comment]
hey @eduardoallegrini I did some updates, let me know if you see anything else.

**Comment by eduardoallegrini** [comment]
Just started reviewing :)

**Comment by eduardoallegrini** [comment]
Hey @matuzalemsteles I'm sorry but there are still some problems, I would like to help and add some fixes but I can't right now, I can only point out the issues.

I'm attaching a video sample, I think it's easier to follow what I mean https://drive.google.com/file/d/1Sf4G8yYhJItoTGINzbcGqmPmkjaJAMHh/view?usp=sharing

1) after changing to the tab `CSS / Markup` the content (probably a long title) generates a space on the right side
2) changing to a smaller device (I'm not sure which is the minimum supported size) or even changing the to the tab `CSS / Markup`, the header somehow loses its sticky property
3) opening the navigation dropdown in the smaller device cause a bottom-page-spacing problem

**Comment by matuzalemsteles** [comment]
hey @eduardoallegrini np, thanks, I just noticed other issues when I was showing the site to other people on a larger monitor.

**Comment by matuzalemsteles** [comment]
hey @eduardoallegrini I made the visual corrections and I will go ahead with this to see it live, I can not reproduce the Sidebar case on the small screen, if it still persists feel free to open an issue.

**Pull request merged**
