### PR TITLE
feat(clayui.com): Add documentation on creating pages for clayui.com

### LINKED ISSUE #3692: Document how Clay builds its pages using Gatsby
I'd like it if we had a document of how the backbone of Clay's page creation works to ease onboarding someone new on Clay.
Talking about `createPages.js`, `docs.js`, `onCreateNode.js`, etc.

The goal of this is to document steps and flow of creation in Clay rather than re-documenting Gatsby features.

We can host this documentation here on GitHub in a form of markdown page, as the goal is to make documentation developer-facing instead of consumer-facing.

### PR DESCRIPTION
**Pull request by kresimir-coko**
Fixes #3692 

I think this covers most of my own learnings and the basics of how pages get created and Gatbsy's workflow in the context of Clay.

I've created a `docs` folder in the root of the repo and added this file to it.

### CODE REVIEW

**Review by matuzalemsteles — COMMENTED** [review]
It looks good, I would just add some links to the Gatsby documentation. Mainly pointing to the Gatsby API lifecycle, this helps to have a better understanding for those who arrive as well.

**Comment by bryceosterhaus** [comment]
Looks good to me as well, and I agree with Matu, I think it'd be good to back-link to gatsby to ensure its up to date.

**Comment by kresimir-coko** [comment]
I've added some links to Gatsby that @matuzalemsteles linked me before in this [comment](https://github.com/liferay/clay/pull/3477#pullrequestreview-451993747)

**Review by matuzalemsteles — APPROVED** [review]
LGTM! I think we can start with that if someone misses something else we can send another PR and add more information.

**Pull request merged**
