### PR TITLE
fix(@clayui/card): prevent double 'card' class on ClayCardWithHorizontal

### PR DESCRIPTION
**Pull request by markocikos**
Fixes: https://github.com/liferay/clay/issues/3789

In this PR we are removing the case of double `card` class:
- Outer class is [added](https://github.com/liferay/clay/blob/master/packages/clay-card/src/Card.tsx#L71) when `!selectable`
- Inner class is [added](https://github.com/liferay/clay/blob/master/packages/clay-card/src/Body.tsx#L24-L26) when the card is `horizontal` and `!interactive`. 

In analysis I found that removing inner card would we problematic, but removing outer would be doable after we remove the only case that relies on outer CSS class: horizontal interactive card. We achieved this with navigation card, so we're good to go.

As this is released, we need to update server side rendering in horizontal tag to match markup, specifically we need to delete [these three lines](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/HorizontalCardTag.java#L114-L116):
```
else {
	cssClasses.add("card");
}
```

Notes:
- This is no longer a fix for a blocker, as the case in the original ticket was fixed by a different solution, a navigation card. This is now more of an improvement, to prevent future headaches.
- There is a bit of SF in this PR: `(horizontal && interactive) || interactive` is the same as `interactive`
- `|| undefined` on the end of `classNames` is to prevent `class=""` in markup. See more [here](https://github.com/JedWatson/classnames/issues/115).

@carloslancha @julien

### CODE REVIEW

**Comment by markocikos** [comment]
Hmm, `yarn test` on the whole repo is passing locally. :thinking: 

Honestly, if this PR starts any complication, I am fine with just closing it and the related ticket.

**Comment by carloslancha** [comment]
This is a genuine "Looks not SO horrible to me".

We need to take a deeper look to all this logic, it's too difficult to understand, I spotted a couple of redundant condition and I'm pretty sure that we'll be facing more issues like this one.

The sentence @markocikos told me when I asked some stuff about this "that was my first approach but I quickly went into a rabbit hole" is enough to me to think that this should be refactor/rewritten/simplify/whatever.

So let's move on with this one but we need to take some time to simplify this.

**Comment by matuzalemsteles** [comment]
Yeah I agree, these are some of the visions I had for ClayCard too, I sent an alternative to that in PR #3827. I made some initial changes and added some comments.

**Comment by markocikos** [comment]
@carloslancha I reverted the markup cleanup and updated test. I squashed the last commit it with previous `auto SF` commit for easier review.

**Comment by carloslancha** [comment]
Thanks @markocikos !

@matuzalemsteles we're going with this solution for now since your refactor changes a lot of markup (that looks pretty good) and we're a bit worried about breaking something including it on this release without testing it properly in DXP and we need this release ASAP just to close the card tags migration epic and a support issue.

We can go with yours in the next release, so we can have the time to test it. Sounds right?

Thx everyone!

**Comment by matuzalemsteles** [comment]
@carloslancha no problem, we can look at it with better attention anyway.

**Pull request merged**
