### PR TITLE
feat(clay-css): Add usable mixins from bourbon

### PR DESCRIPTION
**Pull request by eduardoallegrini**

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
https://issues.liferay.com/browse/LPS-95490
In order to clean the portal from some old mixins library like bourbon, we are removing the usages from different parts of the portal but there are some still-usable mixins we should include in Clay

**Comment by jbalsas** [comment]
@matuzalemsteles, @pat270, could you make sure this gets in for the `2.x` release so we can continue updating our mixin usage next week? 😘

**Comment by pat270** [comment]
@jbalsas @eduardoallegrini  are we using autoprefixer only on the theme level or does it apply to module css also?

**Comment by pat270** [comment]
New pulls:
3.x https://github.com/liferay/clay/pull/2326
2.x https://github.com/liferay/clay/pull/2325

**Pull request closed without merging**
