### PR TITLE
fix(@clayui/css): Sidebar should be able to overwrite focus styles on sidenav-start and sidenav-end

### LINKED ISSUE #5264: @clayui/css: Sidebar focus style does not show for .sidenav-start .sidebar-light
Sidebar focus styles are overwritten by box-shadow in `.sidenav-start .sidenav-light`. See https://github.com/liferay/clay/pull/5257#pullrequestreview-1223665834

### PR DESCRIPTION
**Pull request by pat270**
fixes #5264

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
Hey @pat270 I thought the focus would be on the Vertical Bar panel, also expect the first iteration of this to already have the focus on the `.sidebar` but it looks like it was for other use cases.

Screen Shot 2022-12-21 at 4 27 54 PM

**Comment by pat270** [comment]
@matuzalemsteles I'm not sure what you mean. Is it this:

whole-panel

**Comment by pat270** [comment]
@matuzalemsteles thanks for the clarification. I just pushed up the fix.

sidenav-start

**Review by matuzalemsteles — APPROVED** [review]
LGTM

**Pull request merged**
