### PR TITLE
chore(release): publish updated packages

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
going to merge this to keep stable up to date with the latest release

**Comment by carloslancha** [comment]
Hey @bryceosterhaus I thought this wasn't intended to be merged

>Create a draft PR against stable (not intended to be merged) to the clay repo; the sole purpose of this is to see CI green one last time before pushing the tag.

If this is the expected process to follow could we update the contributing document? :D

**Comment by bryceosterhaus** [comment]
@carloslancha it's not intended to be merged because of the other step which is

> 6. Once CI is green, run  `git push $REMOTE master:stable`

I had noticed that wasn't run and merging achieves the same purpose, so I just went with that. 

The reason `stable` needs to be up to date is for the docs site and storybook. They are both built off of the latest `stable` branch.

**Comment by bryceosterhaus** [comment]
That step may have still been intended, but I saw it had been several hours so I assumed it was just missed.

**Comment by carloslancha** [comment]
Mmmm I'd swear I ran that command too. Gotcha 👍

**Pull request merged**
