### PR TITLE
chore(ci): only build src and not types for ci

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Going to keep this PR open to see how build time decreases with each change.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
@wincent looks like just removing types from the build process speeds it up quite a bit.

**Comment by wincent** [comment]
Yeah, that's a nice speed up: 7 minutes, down from 12 minutes, although I imagine there is probably a fair bit of variability between runs. The other checks seem to run in about 6 minutes (not sure, because only some of them show the actual time), so seeing as they run in parallel and not serially, 7 minutes is already pretty good.

Just one doubt: is there any conceivable way that building the types might fail even if the rest of the build succeeds?

**Comment by bryceosterhaus** [comment]
> Just one doubt: is there any conceivable way that building the types might fail even if the rest of the build succeeds?

I don't think there is any chance this would happen since we are using the the same tsconfig. There might be a super edge case but I don't think we would need to worry about it. Additionally, we would still be verifying that it builds when we publish, so we would run into issues there if it did break.

**Comment by bryceosterhaus** [comment]
reopening to trigger ci again

**Pull request merged**
