### PR TITLE
chore(@clayui/form): Initial documentation setup for DualListBox and SelectBox

### PR DESCRIPTION
**Pull request by kresimir-coko**
Hey @bryceosterhaus I've made a first version of the documentation to see if the file structure is correct and if this is the type of documentation we wanted in the first place.

If you're willing let me know give me some guidance regarding how to go forward, it seems kinda overwhelming with writing down paragraphs and deciding which examples to showcase.

Also the selecting functionality doesn't work in the mdx files, idk what I'm missing there to get it working.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
Hey @kresimir-coko this is great! We can start with this basic info and add more on demos and paragraphs as needed. I also noticed that the selecting of items didnt work in the code examples, I tried to debug it for a bit but couldn't seem to pin point it. You might try investigating `react-live` which is our how we render those inline react examples. I would even try without ClaySelectBox and see if you are able to reproduce at all. Very odd that doesnt work though.

**Comment by kresimir-coko** [comment]
Vanilla `select` works fine, I couldn't figure out why the selecting doesn't work. react-live documentation is lacking in that regard.

I've pushed a commit containing some cleanup and additions of documentation that were missing, like the html example code and tidied up headings and descriptions.

**Comment by bryceosterhaus** [comment]
I opened a new issue on react-live at https://github.com/FormidableLabs/react-live/issues/196.

Hopefully that will provide some direction

**Comment by bryceosterhaus** [comment]
Updated and added the note about the select functionality not working at https://github.com/liferay/clay/pull/3076

**Pull request closed without merging**
