### PR TITLE
docs(clayui.com): Move input-group to own section

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPD-22854

### CODE REVIEW

**Review by matuzalemsteles — APPROVED** [review]
LGTM! Just one doubt I still have regarding whether we should keep these examples that are in the Markup session or if we want to keep just a few use cases like we are doing in other components. @drakonux @emiliano-cicero thoughts? I didn't see anything explicit about this in the ticket or document just to know if this is ok.

**Comment by drakonux** [comment]
Separating these items is recommended, especially since we'll need to provide extensive design documentation for input groups. If you could review how we're currently giving input groups in the Figma library, we may be able to improve the content.

image

After speaking with @marcoscv-work, it seems that input groups are used in multiple cases, so for us, they are just the ones included in the Figma Library.

**Comment by matuzalemsteles** [comment]
Thanks @drakonux. @pat270 you can check this, apparently everything is ok.

**Comment by pat270** [comment]
@matuzalemsteles I updated the examples to better match with examples in the Figma.

**Review by matuzalemsteles — APPROVED** [review]
LGTM

**Pull request merged**
