### PR TITLE
docs(clayui.com): Moves some sections

### LINKED ISSUE #4630: clayui.com move CSS Framework docs to the main nav
We should remove the CSS Framework section and move the contents into the main flow of the nav. Our component docs have Example, Markup, and API tabs and the CSS Framework separation is no longer needed. We should move:

|Old Section|New Section|
|---|---|
|SCSS|Get Started?|
|Color|Components|
|Grid|Components|
|Typography|Components|
|C Kbd|Components|
|Utilities|Utilities (Create a new section under components)|

### PR DESCRIPTION
**Pull request by pat270**
@matuzalemsteles I moved the sections, but now I'm thinking this might be a bad idea. I just saw someone link the utilities section in Slack. This would definitely break the link and I didn't set up a redirect. I'm good with not making these changes for the sake of reducing confusion.

fixes #4630

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
Hey @pat270 we can create redirect links to this new page by adding the `redirectFrom` property to the frontmatter.

I'm thinking now of separating some things from sessions 😅, to create the Foundations session, to leave some things like:

- Color
- Layout/Grid
- Typography
- Iconography/Icon

What do you think?

**Comment by pat270** [comment]
@matuzalemsteles I did the same thing and saw the redirect for color, https://github.com/liferay/clay/blame/2fe162aa670d59206b561b0b4deeba5872ac9b99/clayui.com/content/docs/css/color.mdx#L3. We're just moving it back to where it was in the past 🤷‍♂️.

**Comment by matuzalemsteles** [comment]
Oh no, apparently, everything is being cyclical 😂

**Comment by julien** [comment]
@pat270 not sure there's still work to be done on this, but I see a conflict.

**Comment by pat270** [comment]
Hey Guys, I'm going to close this. I realize it's pretty jarring to have stuff moved around after we've had docs up for years.

**Pull request closed without merging**
