### PR TITLE
Update dropdown | Fixes #619

### LINKED ISSUE #619: form-groups in a dropdown
We need to use form-groups in a dropdown, we can place all form-groups in the same 'dropdown-section' but the form-group margin-bottom should be 1rem

Now:
image

form-group with margin-bottom: 1rem
image

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by carloslancha** [comment]
@marcoscv-work could you please add an example?

**Comment by pat270** [comment]
Hey @marcoscv-work,

`$dropdown-item-indicator-spacer-*` should only be used to space `.dropdown-item-indicator` in http://pat270.github.io/lexicon/content/dropdowns/#dropdown-menu-with-indicators. We also need to make sure the total space between `.dropdown-section .form-group` and `.dropdown-item` is also equivalent to `$dropdown-item-padding-y * 2` (1rem in Atlas, 0.5rem in Base).

**Comment by pat270** [comment]
One thing I saw somewhere (I forget where) is that dropdown with search should be 32px tall? Should the form elements in #619 also be 32px tall?

**Comment by victorvalle** [comment]
Lexicon team members have been talking and in advance search we want the fields to be 32px height. But we don't want it as a general rule right now for different reasons we would like to study further.

**Comment by marcoscv-work** [comment]
So we could use "form-control-sm" by the moment to set the height to 32px, do we agree?

image

About the space between form-control
@pat270 Can you accommodate the var name and merge?

**Comment by pat270** [comment]
I sent an update. I'm closing this in favor of https://github.com/liferay/clay/pull/636.

**Pull request closed without merging**
