### PR TITLE
chore: run tests through github actions

### PR DESCRIPTION
**Pull request by bryceosterhaus**
I had this idea after working with the gh workflows. This would allow us to not have to rely on travis.ci anymore. Not that travis is bad, but I think the experience is a bit more uniform if we keep most ci related stuff through actions. This also allows us to break up the "ci" task into more descriptive parts, see the image below.

Screen Shot 2020-04-30 at 12 12 46 PM

Anyone opposed to this? It also seems to run about one minute faster than travis.

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
My full support to merge this 🚀. Great work!!!

**Comment by bryceosterhaus** [comment]
resent https://github.com/liferay/clay/pull/3189

I can't seem to get coveralls working properly

**Comment by wincent** [comment]
> Anyone opposed to this?

Nope. In the other repos I've been slowly moving stuff over to GitHub actions because they seem to be more reliable than Travis.

**Comment by jbalsas** [comment]
> Anyone opposed to this?

shipit

**Pull request closed without merging**
