### PR TITLE
fix(clayui.com) landing proposal to fix accessibility issues #3616

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
This PR fixes #3616 

- The last commit is only a cosmetic change

A preview:

clay_site_01

**Comment by matuzalemsteles** [comment]
@marcoscv-work great work!! Maybe just a few visual considerations, just my opinion 🙂.

- We can move the alert message over the header and use `.alert-light`, so it will be smoother and does not break with the hero's harmonization. Screen Shot 2020-08-17 at 14 07 41
- In the "Components" and "CSS" sessions, we can slightly decrease the brown color load and soften the texts with a little bit of gray, this removes some of the excess color.
Screen Shot 2020-08-17 at 14 12 15

Other changes not related to the visual would be just to check the CI's eslint errors and correct the commit messages just to follow the bot's criteria, `<type>(<scope>): <subject>`. Other than that I'm fine with that.

**Comment by eduardoallegrini** [comment]
I like the design _but_ as I said in https://github.com/liferay/clay/issues/3056#issuecomment-607102750 I rather have "minimal" homepage with logo, search-bar and most useful content in small cards - (Google style)

image

**Comment by marcoscv-work** [comment]
> I like the design _but_ as I said in [#3056 (comment)](https://github.com/liferay/clay/issues/3056#issuecomment-607102750) I rather have "minimal" homepage with logo, search-bar and most useful content in small cards - (Google style)
> 
> image

Digital design is about to provide what people want o need to commit a task / to learn / understand.

Google homepage is mainly a search engine and does not need an introduction about what it is or provide context, the focus of Google home page is only "search thinks" that's the reason for a page with a logo and input search.

Clay needs to be explained and introduced or even warning some critical points, those text in the home page are important because they should explain what Clay is and some other important points, this information will be indexed and associated with our "clay". 

that being said, it seems fine to me if we work to reduce of improving the homepage text and information and if we are able to provide in a better way what the objective public needs on our homepage, great!.

**Comment by marcoscv-work** [comment]
Fixing issues and applying @mateomustapic suggestions in another PR

**Pull request closed without merging**
