### PR TITLE
refactor(@clayui/treeview): LPD-19473 Improve TreeView Contrast on Active and Hover states

### PR DESCRIPTION
**Pull request by ilzamcmed**
Jira issue: https://liferay.atlassian.net/browse/LPD-19473

Evidence:
https://github.com/liferay/clay/assets/47724428/2626eb39-a74a-49a7-b1d5-2a7a07b99dac

### CODE REVIEW

**Comment by ilzamcmed** [comment]
Hey @matuzalemsteles @pat270 @ethib137 
This PR is ready for review!
Thanks!

**Comment by pat270** [comment]
@ilzamcmed there are issues with open tree view items getting the active selected state.
active-class
We need to remove the changes from `active-class`. We also need to add `active: (focus: ())` styles and update treeview-dark too.

**Comment by ilzamcmed** [comment]
Thanks @pat270!
I'll work on those behaviors.

**Comment by pat270** [comment]
@ilzamcmed I took a look and updated the borders to use box-shadow instead of border. It keeps the styles more consistent when the state changes.

box-shadow

**Comment by ilzamcmed** [comment]
Thanks @pat270!!

**Pull request merged**
