### PR TITLE
fix(@clayui/css): Deprecate unused Bootstrap 4 components

### PR DESCRIPTION
**Pull request by pat270**
#4205

I still need to add documentation on deprecated components. I'm thinking we should include it in Getting Started under deprecated (idk) since none of these components are documented on clayui.com? 

This pr adds a setting `$enable-bs4-deprecated: false;` and deprecates the Bootstrap 4 components:
- Cards
    - `.card-header-tabs`, `.card-header-pills`, `.card-img-*`, `.card-deck`, `.card-group`, `.card-columns`, `.accordion`
- Carousel
- Custom Forms
    - `.custom-switch`, `.custom-select`, `.custom-select-lg`, `.custom-select-sm`, `.custom-file`, `.custom-range`
- HTML5 Form Validation
    - `.was-validated`, `.invalid-feedback`, `.valid-feedback`, `.#{$state}-feedback`, `.#{$state}-tooltip`
- Form
    - `.col-form-label`, `.col-form-label-lg`, `.col-form-label-sm`, `.form-row`, `.form-inline`
- Jumbotron
- Nav Pills
- Spinners
- Toasts
- Clay CSS Component Table Drag. This was implemented in DXP.

```
Before:
atlas.css: 610kb
atlas.css.gz: 72kb
base.css: 563kb
base.css.gz: 67kb

After:
atlas.css: 583kb (27kb reduction)
atlas.css.gz: 68kb (4kb reduction)
base.css: 536kb (27kb reduction)
base.css.gz: 63kb (4kb reduction)
```

### CODE REVIEW

**Review by matuzalemsteles — COMMENTED** [review]
@pat270 that's interesting, I took a look at the archives to see if we had some related documents on clayui.com but we really don't have what could be good for this case that we can know that maybe people don't use, maybe clients should use due to bootstrap.

In terms of adding this information in some doc, the best case would be to create a blog post about it on clayui.com to talk about it, how to activate it, why we're doing it, and what the goal is. We can create a new Settings documentation to talk about enabling these features via a variable and saying what this will enable can be a way too.

I'm still wondering if the best way here would be to leave this still in v3 and wait for v4 to remove it, it's kind of counterintuitive to remove this now if the goal is just to shrink our bundle, we know it will shrink but that wouldn't be critical for now I'm not sure but if there is an option to keep the flag enabled by default and remove in v4 I think that would be the ideal scenario. It's very difficult to know who isn't using it or if there really is someone using it, especially saying that Clay CSS is also used outside the Liferay.

**Comment by pat270** [comment]
@matuzalemsteles we can set `$enable-bs4-deprecated: true;`. It will output all those components. You're right, it's probably better to leave it in and let people opt out of it. Removing it in V4 sounds good, but I'm guessing we will have to provide some kind of fallback if others are using it. I think we can disable in V4 and remove in V5 😆 .

Blog post sounds good I will take a look at writing something up.

**Comment by matuzalemsteles** [comment]
> Removing it in V4 sounds good, but I'm guessing we will have to provide some kind of fallback if others are using it. I think we can disable in V4 and remove in V5 😆 .

😅 Well, we can do that, hopefully, it doesn't take too long to remove 🙂. In this version we can say that we are deprecating these bootstrap components and that people should start using others instead. The blog post would be a great place to talk about this and the depreciation plan.

**Comment by nhpatt** [comment]
Just to reiterate ideally we should do these changes in a 3 step process, first opt-in (I have a flag that enables me to remove those bootstrap components), then opt-out (a flag to add/enable them), the remove all together.

Seems hard for these kind of changes but we should not remove them directly at least without deprecating them first in one version (this one for example).

**Comment by matuzalemsteles** [comment]
@nhpatt Yeah, I agree. I think it's safe to remove this in v5 completely and in v4 add the flag to enable. It would be good to prepare a blog post on clayui.com to inform you about this plan and if it involves other components, if you need help I can help you.

**Comment by nhpatt** [comment]
I'm not so sure about the versions as they are usually very costly for external developers (it's something that we can discuss when planning the release). But I would deprecate with a flag to remove now if possible.

**Comment by pat270** [comment]
Thanks for the feedback guys, I changed the flag to be opt-in for disabling. This outputs all the CSS unless you set `$enable-bs4-deprecated: false !default;`

**Review by matuzalemsteles — APPROVED** [review]
LGTM

**Pull request merged**
