### PR TITLE
fix(css): allow newline characters to display properly for tooltips

### LINKED ISSUE #2836: ClayTooltipProvider doesn't support newline characters
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?
- Create an element within `ClayTooltipProvider` and pass a string with `\n` newline character(s) in the `title` attribute
- Observe that newlines are not visible in the rendered content, though they show when inspecting the DOM

## What is the expected result?
Newline characters should be honored 

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.0.5  |
| React |         |

### PR DESCRIPTION
**Pull request by bryceosterhaus**
fixes #2836

### CODE REVIEW

**Comment by kresimir-coko** [comment]
Hey @bryceosterhaus Just a quick question related to this. When we make any functionality changes, basically `feats` related to components, even if they are in `css` files we need to add an entry in `stories` for them so they show up in the Storybook?

**Comment by bryceosterhaus** [comment]
@kresimir-coko its not required to always make a new story, but I typically try to create stories to showcase requests that people have had. For this case, I thought it was helpful to add a story since the corresponding issue was related to the TooltipProvider component. So essentially its nice to add for people to see, but not required for every feat.

**Comment by bryceosterhaus** [comment]
@pat270 I'll let you verify this before I merge. I always second guess myself when it comes to css.

**Comment by pat270** [comment]
@bryceosterhaus it LGTM!

**Pull request merged**
