### PR TITLE
chore(demos): add recharts examples to storybook

### PR DESCRIPTION
**Pull request by bryceosterhaus**
I spent some time re-creating our existing charts using `recharts` and overall the experience was really nice. Recharts was super easy to use and highly configurable. I haven't approached the predictive or geomap charts yet, I am going to look into those now.

One question I have for people, is how would you expect us to offer the "clay" portion of charts? Is exporting colors and potentially custom components such as tooltips, legends, and axis enough? Or do you expect something else? I am hesitant to wrap rechart components and export them with our own default config. Check out the storybook for clay-recharts(name subject to change) and let me know what you all think.

### CODE REVIEW

**Comment by julien** [comment]
Hey @bryceosterhaus, 

I think this is actually an improvement compared to what we had before in the sense that `recharts` seems much more "React friendly" than `billboard.js` - The only thing I was initially worried about is if we would be able to use the same features defined by Lexicon such as custom shapes, patterns and colors but this all seems possible. 

> One question I have for people, is how would you expect us to offer the "clay" portion of charts? Is exporting colors and potentially custom components such as tooltips, legends, and axis enough?

I also think that as a first step that would be enough.

**Comment by bryceosterhaus** [comment]
I went ahead and updated some of the examples and built out a custom Clay tooltip.

@matuzalemsteles I tried to take the approach of providing Clay specific components such as `ClayLine`, however it quickly grew very complicated. For example, if we have multiple lines in a chart, we need to make sure they iterate through the list of default Clay colors. I investigated a few routes to do this, but they all became complicated quickly, so I almost want to lean on the side of giving examples instead of baked out components. If we wanted to build it out, it would require us to have some wrapper around Recharts that would contain a global store and keep track of the number of components and assign them proper colors and shapes. 

I'm thinking of just providing the colors and Tooltip for now, and then slowly iterate where teams need it. If we err on the side just creating a lot of examples, it gives us flexibility and we can help coach teams on best ways to implement a given chart. I think its going to be pretty common for teams to have drastically different use cases.

cc @jbalsas what are your thoughts on this?

**Comment by jbalsas** [comment]
Hey @bryceosterhaus, 

> I tried to take the approach of providing Clay specific components such as ClayLine, however it quickly grew very complicated. For example, if we have multiple lines in a chart, we need to make sure they iterate through the list of default Clay colors. I investigated a few routes to do this, but they all became complicated quickly, so I almost want to lean on the side of giving examples instead of baked out components. 

I understand the feeling. My initial reaction is that as it is right now, with this change we're losing more than gaining... 

We should be 200% sure that at least recharts solves the problems that were brought up at https://github.com/liferay/clay/issues/2577 and also that we make it super simple to build consistent/accessible charts (see https://liferay.design/articles/2018/building-charts-for-multiple-products for some reference and context).

Off the top of my head we want to make sure that our new approach is:

Feature | Check
--- | ---
Easily composable from low level | ✅ 
Performant (ie: 20 charts with 2000 points together) | 
Themable |
Customizable |
Consistent |
Accessible |

> If we wanted to build it out, it would require us to have some wrapper around Recharts that would contain a global store and keep track of the number of components and assign them proper colors and shapes.

I would say this shouldn't be so bad... inevitably, whoever using this will end up making some wrappers, otherwise they'd need to make sure to pick the proper colors over and over, show axis and whatnot...

What if high-level mostly just worked with `DATA`?

```javascript
<LineChart data={DATA} height={300} width={500}>
    <CartesianGrid />
    <XAxis dataKey="name" />
    <YAxis />
    <Tooltip />
    <Legend />
    <Line dataKey="pv" stroke={COLORS[0]} />
    <Line dataKey="uv" stroke={COLORS[1]} />
</LineChart>
```

could be:

```javascript
<ClayLineChart data={DATA} height={300} dataKeys=["pv", "uv"] xDataKey="name" width={500} />

ClayLineChart = ({dataKeys, xAxisKey, ...otherProps}) => {
    return (
        <LineChart ...otherProps>
            <CartesianGrid />
            <XAxis dataKey="{xDataKey}" />
            <YAxis />
            <Tooltip />
            <Legend />
            {dataKeys.map(key, index) => <Line dataKey="{key}" stroke={COLORS[index]} />}
        </LineChart>
    );
}
```

We could try to model a bit more and map config to components and support children, although I wouldn't push for this right now.

```javascript
const chartConfig = {
    cartesianGrid: true,
    data: DATA
    height: 300,
    legend: {
        iconType: "wye"
        layout: "vertical"
    },
    tooltip: <CustomTooltip />,
    width: 500
};

<ClayLineChart config={chartConfig}>
    <ReferenceLine x="Page C" stroke="green" label="Min PAGE" />
</ClayLineChart>
```

Just to reiterate, to me key elements we're looking for (in order of importance) should be:
- Performance
- Clear OOTB offering 
- Composability

Similar to what we do with `billboard.js`, we could offer raw `recharts` plus our wrappers for simplicity.

What do you think?

**Comment by bryceosterhaus** [comment]
@jbalsas at this point I think I would want to avoid any high-level components, if we start with just offering the low-level and giving some patterns, I think it will then help us establish patterns for future high-level components we might want. I think we struggled with billboard because it was too much config and really hard to customize small things. So far in my experience with just using recharts, its already been 10x easier and more fun to use than our implementation of billboard ever was.

I agree with you on the priorities but I would probably go about implementing it in phases. By doing this, I think we give ourselves flexibility and also helps us grow in the direction of need, rather than creating a bunch of wrapper before hand. I would imagine the phases looking like..

1. Give devs the thumbs up to use `recharts` and then expose an easily consumable configuration.
2. As devs find themselves running into common issues, we would help provide a solution.
3. As common solutions are solved, we start to provide high-level components for them to easily consume for their use case.

Would this make sense to you? I am curious how other teams would feel by just offering that first phase right now. From my experience as a user of Charts, I think just giving them recharts is already a huge headache removed.

cc: @kienD, I'm curious what your team would think about this.

**Comment by jbalsas** [comment]
Hey @bryceosterhaus!

> I agree with you on the priorities but I would probably go about implementing it in phases.

I don't see anything wrong with that 😉 

> 1. Give devs the thumbs up to use recharts and then expose an easily consumable configuration.

I would want to do: **0a. Triple check recharts covers our performance requirements**
I would want to do: **0b. Check with legal if `recharts` use and redistribution is ok**

Then I would prefer if we swap the order in 1 to: -> **1. Expose an easily consumable configuration and give the devs the thumbs up to use recharts**. 

This last part worries me a little bit though... we'll want to lock down a specific version but that's also brought us some problems in the past, so we need to tread lightly there, but since `Analytics Cloud` is likely the only one to start with this, we can leave it open and up to them.

> 2. As devs find themselves running into common issues, we would help provide a solution.

I'm not particularly fond of putting the burden of proof on product teams. I know based on your experience `recharts` should be a much better, but still, exposing them to this raw library could endanger their progress on other features.

I would suggest **we take it on ourselves to apply this at least in one real project collaborating with the responsible team** so we find some of the issues and uncover the pain points (and see the patterns emerge).

> 3. As common solutions are solved, we start to provide high-level components for them to easily consume for their use case.

This should be fine, granted that we've developed real common solutions on our own.

How does that sound?

**Comment by bryceosterhaus** [comment]
Yeah that sounds pretty good to me. My overall goal is to discover the needs first before creating anything high-level. I also don't anticipate being able to make a 1-for-1 copy of billboards styles, not sure how much of an issue this is though.

> 0a. Triple check recharts covers our performance requirements
> 0b. Check with legal if recharts use and redistribution is ok

I'll try to create a performance example today. As for as legal goes, who is the best person to ping about this?

> I'm not particularly fond of putting the burden of proof on Product Teams. I know based on your experience recharts will be much better, but still, exposing them to this raw library could endanger their progress on other features.

Ideally we would be able to iterate sooner than later. Meaning that hopefully with even AC moving to recharts, or at least slowly adopting them. We would start to see patterns. Right now, the hard part about creating high-level charts is that we are creating based off of "unknown" needs and really the only way to figure out what those needs are, is by having product teams bring those to us.

> I would suggest we take it on ourselves to apply this at least in one real project collaborating with the responsible team so we find some of the issues and uncover the pain points (and see the patterns emerge).

I'd be more than happy to take this on and work with a product team to revamp their charts. Is there a particular team that has a smaller charts foot print than AC that we could tackle?

**Comment by jbalsas** [comment]
> I pinged Matija about the legal portion of this

Excellent... You should create an inbound licensing ticket in JIRA . See our [React-dnd Usage](https://issues.liferay.com/browse/FOSS-52) for reference.

> I'd be more than happy to take this on and work with a product team to revamp their charts. Is there a particular team that has a smaller charts foot print than AC that we could tackle?

We're [using LineChart in Workflow Metrics](https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/portal-workflow/portal-workflow-metrics-web/src/main/resources/META-INF/resources/js/components/process-metrics/completion-velocity/VelocityChart.es.js#L12). This could be a good starting point, but I presume we'll still need to tackle AC for a bigger picture.

I think Commerce might be using some, but maybe through jsp tags... @FabioDiegoMastrorilli, @marco-leo, could you confirm and weigh in if necessary?

**Comment by FabioDiegoMastrorilli** [comment]
> > I pinged Matija about the legal portion of this
> 
> Excellent... You should create an inbound licensing ticket in JIRA . See our [React-dnd Usage](https://issues.liferay.com/browse/FOSS-52) for reference.
> 
> > I'd be more than happy to take this on and work with a product team to revamp their charts. Is there a particular team that has a smaller charts foot print than AC that we could tackle?
> 
> We're [using LineChart in Workflow Metrics](https://github.com/liferay/liferay-portal/blob/master/modules/dxp/apps/portal-workflow/portal-workflow-metrics-web/src/main/resources/META-INF/resources/js/components/process-metrics/completion-velocity/VelocityChart.es.js#L12). This could be a good starting point, but I presume we'll still need to tackle AC for a bigger picture.
> 
> I think Commerce might be using some, but maybe through jsp tags... @FabioDiegoMastrorilli, @marco-leo, could you confirm and weigh in if necessary?

At the moment we don't use taglibs to wrap charts, but I'm pretty sure we've used them via js module in our machine learning related modules. @gcmznt surely knows more than me :)

**Comment by kienD** [comment]
> @jbalsas at this point I think I would want to avoid any high-level components, if we start with just offering the low-level and giving some patterns, I think it will then help us establish patterns for future high-level components we might want. I think we struggled with billboard because it was too much config and really hard to customize small things. So far in my experience with just using recharts, its already been 10x easier and more fun to use than our implementation of billboard ever was.
> 
> I agree with you on the priorities but I would probably go about implementing it in phases. By doing this, I think we give ourselves flexibility and also helps us grow in the direction of need, rather than creating a bunch of wrapper before hand. I would imagine the phases looking like..
> 
>     1. Give devs the thumbs up to use `recharts` and then expose an easily consumable configuration.
> 
>     2. As devs find themselves running into common issues, we would help provide a solution.
> 
>     3. As common solutions are solved, we start to provide high-level components for them to easily consume for their use case.
> 
> 
> Would this make sense to you? I am curious how other teams would feel by just offering that first phase right now. From my experience as a user of Charts, I think just giving them recharts is already a huge headache removed.
> 
> cc: @kienD, I'm curious what your team would think about this.

@bryceosterhaus, we're open to using recharts as a standalone charting library for now.  I tried to do a quick conversion of a couple of our charts from billboardjs to recharts and had a relatively easy time doing so.  

It seems like it'll be easier to develop with recharts due to it's flexibility.

**Comment by bryceosterhaus** [comment]
@jbalsas  Checkout this for a crude implementation for a performance test of multiple charts. I also reached out to AC team for data that they were having issues with. https://deploy-preview-2779--storybook-clayui.netlify.com/?path=/story/components-clayrecharts--performance-test

**Comment by bryceosterhaus** [comment]
anyone else have any primary concerns? If so, ill continue to try and address examples within our storybook.

**Comment by matuzalemsteles** [comment]
My view on this is that the biggest pain I saw and received complaints about using the charts was the work that had to be done to make the chart look like Lexicon, this seems to be one of our main issues. Before flexibility, even with recharts it seems easier, people will still have to work on each custom chart to look like Lexicon. I think our cases already exist https://liferay.design/lexicon/core-components/charts/charts/. Does it make sense to you?

**Comment by bryceosterhaus** [comment]
@matuzalemsteles not quite sure what you mean. Are you saying it's easier with recharts or with billboard to make the chart look like lexicon?

**Comment by matuzalemsteles** [comment]
Sorry @bryceosterhaus for the confusion. In fact, I'm saying that although rechart is easier than billboard, people still needed to customize it to get Lexicon cases for those who want to follow, so I think we need to provide a minimum of styles. so people don't have to have this work. I think that was one of the points that people complained about in the beginning.

**Comment by bryceosterhaus** [comment]
@matuzalemsteles Ah I see. Right now the plan is for me to help AC refactor some of their charts using recharts, part of my goal in that is to try and figure out the common uses we can extract to clay itself. After going through AC I think I will have a better idea on which direction to go. Ill keep you updated.

**Comment by matuzalemsteles** [comment]
@bryceosterhaus I see. I think the AC cases are good for this moment but take into consideration the small Liferay teams.

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, that's a great point!

One thing bothered me, though:

> I think we need to provide a minimum of styles. so people don't have to have this work. I think that was one of the points that people complained about in the beginning.

The old version of charts was a very close implementation of the Lexicon charts... do you have a particular example in which this was not the case and the teams struggled to make it look like it? Maybe they struggled with other type of charts outside of those defined by Lexicon and the library and designed elsewhere? Just curious here :)

**Comment by matuzalemsteles** [comment]
Hey @jbalsas, the design problems involving our old graphics compared to Lexicon are the fine details that we didn't have. For example: The [Line Chart](https://liferay.design/lexicon/core-components/charts/chart-line/) graph compared to the [Line Chart in Clay](http://v2.clayui.com/docs/components/charts/basic/line-chart.html), some things that Design notes:

- The edges of the graph that surround are not rounded and do not exist at all ends
- The font size of the labels on the axes, apparently are not the same
- We have some small spacing problems between some elements

These are some things that are observable in what is expected and what we have, there are more in other graphs that we have that are as basic charts. From the point of view of who was using the graphics, they would not need to customize these details, when there was a CEREBRO team here in Brazil (now AC) they complained a lot about these details, especially the design (Rafael was at the time), he was very careful in how the data was presentable, so he found a lot of missing details in how the axes are presented, spacing between them and etc ... In some meetings I had with CEREBRO/Workflow it was that they expected that these graphics delivered by Clay already had these details that were predicted by the Lexicon designers, in their point of view, they wanted a high-level component with all these customizations.

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, thanks for the context! I totally agree with this and this is a good lesson for us when working in the future version of charts.

That being said, there's always some time where design meets reality that we need to get better at addressing. Past is past, so no need to go over this. We should make a good job at producing high-quality out-of-the-box charts... and if they don't 100% match the designs, maybe what we can do is work with Lexicon to adjust them to reality so designers and developers don't see their expectations frustrated.

**Comment by bryceosterhaus** [comment]
@jbalsas @matuzalemsteles what do you guys think of me just moving these examples to the "demos" stories for now?

**Comment by bryceosterhaus** [comment]
I went ahead and moved it to demos. Let me know what you think.

**Comment by jbalsas** [comment]
LGTM @bryceosterhaus! Feel free to merge. 

I've pinged @andresfulla as they were attempting to use our current charts in DXP and finding some trouble with it. We can explore this as well for them rather than having to jump from one version to the other.

**Comment by matuzalemsteles** [comment]
Sounds good for me! Can we release on top of a `v4.0.0-rc.1` version? since we are making a major change.

**Comment by jbalsas** [comment]
As far as I can tell, changes here only involve the site, so we don't even need a new release. We should also be careful with major releases, as that will have a very big impact in our DXP integration and our maintenance costs. If we can roll this out in a semantically responsible way, that'd be ideal :)

We've attempted to use this in DXP and we've had some issues configuring the build including some not-so-pleasant surprises, like recharts dependencies on lodash and node.js native `events` package. This is to say, rolling this out might be a bit more tricky than it seems.

@izaera and @andresfulla might be able to share some more details

**Comment by bryceosterhaus** [comment]
Yeah I don't think think we need to do any versioning for this, this is just an example to showcase for our demos and we won't actually be releasing anything.

> like recharts dependencies on lodash and node.js native events package

Hmm, this seems worrisome, I'll investigate a bit.

**Comment by andresfulla** [comment]
Along with @izaera I included `recharts` in the portal, as I am using the library without Clay. We did it like this: https://github.com/andresfulla/liferay-portal/commit/85dda548e34dc41dc46df168ad4df947830b2bb7

We're using a different `loadash` and providing a node `events` polyfill`.

My idea is to get it on master in the following weeks.

**Comment by wincent** [comment]
> My idea is to get it on master in the following weeks.

Tangential comment on that commit @andresfulla [here](https://github.com/andresfulla/liferay-portal/commit/85dda548e34dc41dc46df168ad4df947830b2bb7#r37172941).

**Comment by andresfulla** [comment]
Just in case it might be relevant. I'm getting a warning about `componentWillReceiveProps` been renamed to `UNSAFE_componentWillReceiveProps` coming from `Line` and `LineChart`.

**Comment by bryceosterhaus** [comment]
hmm, you see those errors on this page? https://storybook.clayui.com/?path=/story/demos-recharts--line

**Comment by andresfulla** [comment]
no, I get it in the portal. On `development` and with `recharts@1.8.5`

**Comment by bryceosterhaus** [comment]
@andresfulla hmm, thats odd we don't see it on the clay side. Regardless, it shouldn't be a huge issue unless they remove those lifecycles in future versions, which I think would be pretty unlikely at this point.

**Pull request merged**
