### PR TITLE
Clayui.com prep CSS so we can toggle between Base/Atlas Theme and other fixes

### PR DESCRIPTION
**Pull request by pat270**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matuzalemsteles** [comment]
hey @pat270 am i wondering if we should apply these changes to v3 also and will it be worth applying these changes to 2.x?

**Comment by pat270** [comment]
@matuzalemsteles Yes these changes are worth applying to v3, but I couldn't get the site to run.

**Comment by matuzalemsteles** [comment]
hey @pat270, no problem as soon as #1525 come in, we can apply this there.

**Comment by pat270** [comment]
@matuzalemsteles sounds good, is it ok to add more updates to this pr?

**Comment by matuzalemsteles** [comment]
@pat270 would recommend working on 3.x, I will try to merge the PR tomorrow so we can continue working on it.

**Comment by matuzalemsteles** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
