### PR TITLE
fix(clay-css): display the dropdown arrow icon on IE11

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you please check my fix?

Thanks, Roland

https://github.com/liferay/clay/issues/3922

### CODE REVIEW

**Comment by rolandpakai** [comment]
Hi @pat270 

could you please check my fix?

Thanks, Roland

**Comment by pat270** [comment]
@rolandpakai this actually doesn't do anything because the bug exists in 3.x also. We hide the default select arrow and replace it with our own icon for consistency. There are two things happening here:
1) Our icon isn't displaying in IE11
2) The pseudo element selector isn't hiding the default arrow in IE11

**Comment by rolandpakai** [comment]
Hi @pat270 

yes, on 3x "our icon" isnt displaying in IE11 but the default arrow at least visible because of the pseudo selector is not hiding it,
On 2x we can see neither of them - here the pseudo selector hides the arrow (display:none)

How can we fix this on 3x and 2x too? Do you have any suggestion? 

Thanks, Roland

**Comment by pat270** [comment]
Closing this in favor of #3926.

**Comment by pat270** [comment]
Hey @rolandpakai looks like I sent it at the same time as your comment. You can see what I did there.

**Comment by rolandpakai** [comment]
Hi @pat270 

thanks for the fix.
I saw it was merged too.
Could you please let me known when will be release the fix in the new v2.22.2 version?

I will update the version in Liferay on this https://issues.liferay.com/browse/LPS-127635

Thanks, Roland

**Comment by pat270** [comment]
@rolandpakai I believe 2.x is released based on demand. @bryceosterhaus Can we cut a new 2.x version? Want me to create an issue for it?

**Comment by bryceosterhaus** [comment]
2.x gets released bi-wekly with the 3.x releases, assuming there have been commits to 2.x during that period.

I am planning to release both 3.x and 2.x today

**Comment by pat270** [comment]
👍 Thanks!

**Pull request closed without merging**
