### PR TITLE
feat(@clayui/css): Utilities adds `.c-feedback` component

### LINKED ISSUE #3968: Feedback Indicator
## Feedback Indicator
Due to [LEXI-765](https://issues.liferay.com/browse/LEXI-765) request by team-tango, we would like to add a new component to give feedback. It's basically a non-boxed alert that has no interaction. However, a link can be placed within the message. 

image

There are 4 types of feedback indicators as we have for alerts. 

image

And as we talked offline instead of the initial name of "alert indicator" use "feedback indicator".

The definition is published on the lexicon [site](https://liferay.design/lexicon/core-components/alerts/#alert-indicator) and you can access [LEXI-916](https://issues.liferay.com/browse/LEXI-916) where we worked. There is a link to the [definition document](https://docs.google.com/document/d/1OmVWBWyTXVbeXFDmkVfU4plLp0BINHtIDbk3aEvt-eg/edit).

If you need additional work or definition please don't hesitate to request it.

### PR DESCRIPTION
**Pull request by pat270**
- Utilities adds Sass maps `$c-feedback`, `$c-feedback-indicator`,
    `$c-feedback-indicator-only-child`, `$c-feedback-lead`, `$c-feedback-text`, `$c-feedback-stacked`, `$c-feedback-stacked-c-feedback`
- Utilities adds variables `$c-feedback-trimmed-spacer`, `$c-feedback-secondary-color`, `$c-feedback-success-color`, `$c-feedback-info-color`, `$c-feedback-warning-color`, `$c-feedback-danger-color`, `$c-feedback-dark-color`
- Add docs

c-feedback

fixes #3968

### CODE REVIEW

**Comment by marcoscv-work** [comment]
LG2M ! 👍

**Comment by marcoscv-work** [comment]
is this PR fixing some issue or some task associated? just asking to know if I can merge it

**Comment by pat270** [comment]
Glad this isnt merged yet, I'm going to mark as draft for now.

**Comment by pat270** [comment]
Going to close this and resend something that requires less work.

**Pull request closed without merging**
