### PR TITLE
(#791) Modal Footer with many items should break to new line

### PR DESCRIPTION
**Pull request by pat270**

### CODE REVIEW

**Comment by jbalsas** [comment]
@carloslancha, @matuzalemsteles, does this mean we need to update the modal component?

**Comment by matuzalemsteles** [comment]
hey @jbalsas, the current markup of our ClayModal follows that of pr, I believe that were more changes in the behavior of CSS. @pat270 confirms? 🙂

**Comment by pat270** [comment]
@matuzalemsteles you are correct. I really wanted to change the mark up though.

**Comment by jbalsas** [comment]
Awesome, thanks guys! 👏

**Pull request merged**
