### PR TITLE
Fix tag type JSDOC when use multiple types | Fixes #736

### LINKED ISSUE #736: `Type` tags are incorrect in JSDOC
When we're ready to go with the generation of API documentation, to get a better representation of what we've documented, we need to follow what's documented at http://usejsdoc.org.

See http://usejsdoc.org/tags-type.html

#### Expected behavior
```javascript
/**
 * @type {(number|boolean)} 
 */
```

#### Current behavior
```javascript
/**
 * @type {number|boolean}
 */
```

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by carloslancha** [comment]
Hey @matuzalemsteles nice work! Could you please order the params alphabetically too?

Current:
```
 	 * @instance
 	 * @memberof ClayAlert
	 * @type {?(string|undefined)}
 	 * @default undefined
```
 Expected:
```
 	 * @default undefined
 	 * @instance
 	 * @memberof ClayAlert
	 * @type {?(string|undefined)}
```

Thx!

**Comment by carloslancha** [comment]
Could you please also do this changes for `clay-charts`?

**Comment by matuzalemsteles** [comment]
Hey @carloslancha, I just forgot to track the changes in `clay-charts` 😅, I'll do it now, thanks!

**Comment by carloslancha** [comment]
Merged, thx!

**Pull request merged**
