### PR TITLE
#600 Breaking Dropdown Action Toggle and Quick Action Item require `.component-action`

### PR DESCRIPTION
**Pull request by matuzalemsteles**
See context #637

Hey @pat270, I do not know if this is expected for Dropdown Actions with `component-action`, the **focus** differs from others, are they expected?

### CODE REVIEW

**Comment by pat270** [comment]
@matuzalemsteles do you have an example or screenshot of what is different about the focus?

**Comment by matuzalemsteles** [comment]
Hey @pat270, Sorry for delay.

For example:
screen shot 2018-03-05 at 09 46 59
screen shot 2018-03-05 at 09 46 46

**Comment by pat270** [comment]
@matuzalemsteles
Lexicon doesn't define any focus state in any of their docs. I changed it to match btn-secondary since they share the same colors. If you want it to be blue we can make it blue, but I still prefer we use the same btn classes across items in management bar (mentioned above) even for dropdown action. It allows us to scope any style changes just to management bar.

Or I can add component action to all the navbars (I implemented this pattern late after I saw more of the site designs).

**Comment by matuzalemsteles** [comment]
Hey @carloslancha, I talked to @pat270 and not is need to use `component-action` in `ClayManagementToolbar`. I think this is ready to go, could you check to see if something is missing?

**Comment by carloslancha** [comment]
@matuzalemsteles @pat270 what is the logic for `component-action` then? Where should and where shouldn't be?

**Comment by pat270** [comment]
@carloslancha The logic for `component-action` is for actions in components, except in Management Bar, Navigation Bar, Application Bar, Pagination, Panels, Progress Bars etc. `component-action` was implemented after a lot of those components and there is no support to customize it at the moment.

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Resent https://github.com/liferay/clay/pull/725

**Pull request closed without merging**
