### PR TITLE
chore: move @clayui/css as a peerDependency

### PR DESCRIPTION
**Pull request by bryceosterhaus**
`@clayui/css` is function more as a peer dependency and not an explicit devDependency. By moving to peerDependencies and by also changing the version to "*" we are communicating that clay components are components based on the latest css release.

Let me know if anyone sees issue with this.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
note, the 4 space tab change was to make sure out package.json's also followed our prettier config.

**Comment by bryceosterhaus** [comment]
Oh good point. Maybe we should do `3.x` instead of `*`. what do you think?

**Comment by matuzalemsteles** [comment]
> Oh good point. Maybe we should do 3.x instead of *. what do you think?

Yeah, I think this is safer.

**Comment by bryceosterhaus** [comment]
updated to 3.x, going to merge

**Pull request merged**
