### PR TITLE
feat(clayui.com): Add Markup/CSS page for Toolbar component

### PR DESCRIPTION
**Pull request by kresimir-coko**
Hey @bryceosterhaus @pat270 I think that both of you can take a look at this and let me know if I've included the examples I was supposed to, taking inspiration from [here](https://github.com/liferay/clay/issues/3219#issuecomment-627505325).

It was tricky sifting through some close-to-duplicate examples, but please do let me know if I missed something or included something that wasn't necessary.

### CODE REVIEW

**Comment by pat270** [comment]
@kresimir-coko The CSS docs probably should go under Toolbar instead of Upper Toolbar. Upper Toolbar is specifically https://liferay.design/lexicon/core-components/toolbars/toolbar-upper/. I don't have any markup for Upper Toolbar. I remember something along the lines of component teams will handle the markup.

We have `subnav-tbar-primary` docs under https://clayui.com/docs/components/management-toolbar.html#css-markup-search and `subnav-tbar-light` under https://clayui.com/docs/components/multi-step-nav.html#simplified. I think it would be ok to duplicate docs with more detail and links to where they're used if/when we create a Toolbar page.

**Comment by jbalsas** [comment]
> Upper Toolbar is specifically https://liferay.design/lexicon/core-components/toolbars/toolbar-upper/. I don't have any markup for Upper Toolbar. I remember something along the lines of component teams will handle the markup.

I think that's `info_bar` in DXP: https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib/src/main/resources/META-INF/resources/info_bar/start.jsp

Might be a good component to bring over. It's heavily used across the board...

**Comment by kresimir-coko** [comment]
Alright, I'll transfer this one into markup for a (as of now) non-existant page Toolbar.

@jbalsas as for bringing over the Info Bar component. 
1. Would that be the Toolbar, Upper Toolbar, or Info Bar component? 
2. If Toolbar or Info Bar, i couldn't find it in Lexicon, so we would need them to make the design for it.
3. If Upper Toolbar, we already have that one

**Comment by jbalsas** [comment]
> If Upper Toolbar, we already have that one

I think this is the case, but maybe @drakonux or @laugardie can confirm...

**Comment by kresimir-coko** [comment]
I've renamed the page from `Upper Toolbar` to just `Toolbar`, to go along with @pat270's comment. 

So if this gets merged as is now:
- the `Upper Toolbar` still doesn't have it's Markup/CSS page, and 
- we'll have a new "component" `Toolbar` that doesn't have a React Component page.

**Comment by drakonux** [comment]
I agree with @pat270 a generic name like [toolbar ](https://liferay.design/lexicon/core-components/toolbars/) fits better about what we are looking for. The Product teams should be able to customize it to show information or whatever they need in the product context.

PS. The upper toolbar is just a DXP convention name for a toolbar they use. We should improve these distinctions in Lexicon Site with clearer descriptions.

**Comment by kresimir-coko** [comment]
Awesome @drakonux let us know when you do that so we can reflect it on Clay!

**Comment by kresimir-coko** [comment]
Hey @bryceosterhaus I think you overlooked this PR or thought it wasn't ready for review because of my latest comment above, but it is ready! :)

**Comment by bryceosterhaus** [comment]
Whoops! My bad. Thanks for reminding me!

**Pull request merged**
