### PR TITLE
docs(clayui.com): Use c-inner for better focus experience

### LINKED ISSUE #3042: Use c-inner for better focus styles
Blue focus outline should only show on keyboard tab, not click

### PR DESCRIPTION
**Pull request by pat270**
Renamed all docs with `nav-toc` from `.md` to `.mdx`. The code changes to doc files are from running `yarn  format:all`.

fixes #3042

going to revisit `nav-toc` later, just used browser default focus styles for now.

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
hey @pat270 one of the things why i left the `.md` pages for CSS was because Gatsby is much faster at processing them differently from `.mdx` files, when they were all in `.mdx` time build was very time consuming and hot reloading too.

**Comment by pat270** [comment]
@matuzalemsteles I see, I suppose I can just keep it `.md` and write out the markup for Table of Contents instead of using markdown. Any objections to that?

**Comment by matuzalemsteles** [comment]
@pat270 no problem for me

**Comment by bryceosterhaus** [comment]
LGTM!

**Pull request merged**
