### PR TITLE
feat(@clayui/css): Adds :focus-visible support

### PR DESCRIPTION
**Pull request by pat270**
This adds `:focus-visible` support by default. All the browsers that we support have this feature, we can disable it by setting `$enable-focus-visible: false`. Most items should be covered except form `input` and `select`, these always show the focus outline.

This also adds the class `c-prefers-focus` to force focus on click via the accessibility menu. I wanted to include docs today, but couldn't get to it today.

Lastly, I didn't cover the style issues in #5624. I feel like it's too much change for this PR.

#3342 #4972 #5006

@ethib137 @matuzalemsteles @marcoscv-work @veroglez

### CODE REVIEW

**Review by matuzalemsteles — COMMENTED** [review]
LGTM! @pat270 how is the use case when we have the focus visible together with the `c-inner`, does it cause any problems? It would be possible for example to have a toggle, for example if the `enable-focus-visible` property is enabled the `enable-c-inner` property is disabled.

**Comment by matuzalemsteles** [comment]
@pat270 I sent a small fix on the breadcrumb that we were using the `c-focus-inset` on the button.

I noticed that some use cases still have the ring perhaps this is expected for the Picker button, right?. I also noticed that we still have the ring in MultiStep.

**Comment by pat270** [comment]
Thanks @matuzalemsteles ! I probably missed several places. I only updated the mixins. I should check the components as well.

**Review by matuzalemsteles — APPROVED** [review]
LGTM!

**Pull request merged**
