### PR TITLE
LPD-29322 - Improve L0 accessible colors to be closer to 3:1 ratio

### PR DESCRIPTION
**Pull request by marcoscv-work**
Related to this Lexicon PR:
https://github.com/liferay-design/liferay.design/pull/1228/

image

### CODE REVIEW

**Review by pat270 — CHANGES_REQUESTED** [review]
@marcoscv-work we need to update the colors in Cadmin also

**Comment by marcoscv-work** [comment]
> @marcoscv-work we need to update the colors in Cadmin also

thanks! I will add those variables!

**Comment by marcoscv-work** [comment]
@pat270 I've already added variables! thanks!

**Comment by pat270** [comment]
@marcoscv-work I decided it's better to use Sass color functions to derive the `L0` colors just in case someone is relying on it. I think we can change the colors to hex in another ticket.

**Review by pat270 — APPROVED** [review]

**Pull request merged**
