### PR TITLE
feat(clay-css): Adds c-inner

### PR DESCRIPTION
**Pull request by pat270**
issue #2763 

@marcoscv-work I was able to save ~10kb by inheriting sizing properties in `.c-inner`. Compressed it's still ~2kb, no savings there.

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
I suppose I'm doing something wrong but I'm not able to see the c-inner focus:

image

**Comment by pat270** [comment]
@marcoscv-work the focus outline is supposed to show on input and submit buttons. Not sure why it's not working on `btn-primary`, it seems to work on my end.

**Comment by marcoscv-work** [comment]
Some strange cache issue in my local, it's working fine! ;-) !

Thanks @pat270 !

**Pull request merged**
