### PR TITLE
feat(clay-css): Sizes for Dropdowns

### LINKED ISSUE #2631: Sizes for Dropdowns
## What is your proposal?
A bigger dropdown. A `size` prop.

## Why would adopting this proposal be beneficial?
I'm using a big dropdown _(although there's some controversy on whether that's a dropdown)_  in the Portal. It will much better and less code if I could just use ClayDropdown, but I can't because it's too narrow for all those Experiences. Screenshot 👇:
Screenshot 2019-10-14 at 11 55 49

## What are the alternatives to this proposal?
An alternative will be to pass props like `className` and `style` from `ClayDropdown` to the actual dropdown _(the one that shows and hides)_ and not the wrapper _(the one containing the `trigger`)_. That way I could do some decent CSS to make it bigger.

Codesandbox with some cheap CSS achieving what I want: https://codesandbox.io/embed/great-keldysh-f272t

Thanks!!

### PR DESCRIPTION
**Pull request by pat270**
fixes #2631 

This adds 6 different dropdown sizes. The markup is:
```
<div class="dropdown-menu dropdown-menu-fluid"></div>
<div class="dropdown-menu dropdown-menu-fluid dropdown-menu-fluid-xl"></div>
<div class="dropdown-menu dropdown-menu-fluid dropdown-menu-fluid-lg"></div>
<div class="dropdown-menu dropdown-menu-fluid dropdown-menu-fluid-md"></div>
<div class="dropdown-menu dropdown-menu-fluid dropdown-menu-fluid-sm"></div>
<div class="dropdown-menu dropdown-menu-fluid dropdown-menu-fluid-xs"></div>
```
You can toss in whatever you want in `dropdown-menu-fluid`. I tried to mimic the screenshot in #2631 by using `sheet` inside the `dropdown-menu`. I got close, but not exact.

I also added `popover-fluid` modifier that removes the default `popover` style. You can toss whatever you want in there too. From my tinkering, I concluded:
```
<div class="popover popover-fluid fade show">
    <div class="dropdown-menu dropdown-menu-fluid dropdown-menu-fluid-xl"></div>
</div>
```
should work best if it's decided to go the popover route.

I'm also thinking this is too big of a change for 2.x.

/cc @bryceosterhaus @andresfulla @jbalsas

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Hey guys, do we really need all those sizes? @andresfulla @jbalsas @victorvalle @drakonux help us!

@pat270 I'm not sure how it works, I'm adding ´dropdown-menu-fluid dropdown-menu-fluid-sm´ to a regular dropdown and is not working as I expected

image

**Comment by andresfulla** [comment]
For my use case (https://github.com/liferay/clay/issues/2631), what I really need is either a big dropdown or a way to interact with it via `<ClayDropdown />` props. Bear in mind that I'm using the `ClayDropdown` as a container without Items.

These classes won't solve my problem unless they come with `<ClayDropdown />` `size` prop that puts them in place, because as far as I know I can't. Hope this makes sense.

**Comment by pat270** [comment]
@marcoscv-work For dropdowns using the Bootstrap plugin, you need to add `dropdown-fluid dropdown-fluid-sm` on `dropdown`. `dropdown-menu-fluid dropdown-menu-fluid-sm` are for dropdown-menus that are appended to the `body` element which I think we do with `ClayDropdown`.

@andresfulla if you can pass css classes to the `dropdown-menu`, my changes should work.

**Comment by victorvalle** [comment]
I don't know the different use cases we have and where these sizes come from. I've seen front-ends having to change the width of this component manually to adapt due to the text length. Maybe is better to ask more front-ends about this specific case and when they remember using them.

**Comment by andresfulla** [comment]
> @marcoscv-work For dropdowns using the Bootstrap plugin, you need to add `dropdown-fluid dropdown-fluid-sm` on `dropdown`. `dropdown-menu-fluid dropdown-menu-fluid-sm` are for dropdown-menus that are appended to the `body` element which I think we do with `ClayDropdown`.
> 
> @andresfulla if you can pass css classes to the `dropdown-menu`, my changes should work.

Thanks. The problem is that I cannot pass the CSS class to the `.dropdown-menu`. The class goes to the `.dropdown`, and `.dropdown-menu` is out of `.dropdown` (via portal).

Perhaps I'm missing a way to do that. Dummy example of what I'm trying to say:
https://codesandbox.io/s/css-classes-in-dropdown-3vk76

Thanks!!!

**Comment by bryceosterhaus** [comment]
@andresfulla you should be able to add any attrs needed to the menu element by passing `menuElementAttrs`. I added to the csb you provide, https://codesandbox.io/s/css-classes-in-dropdown-7yks6

**Comment by andresfulla** [comment]
`menuElementAttrs` prop is honestly all I need. Those sizes for the dropdown still require me to use custom CSS for my use case.

**Comment by pat270** [comment]
> `menuElementAttrs` prop is honestly all I need. Those sizes for the dropdown still require me to use custom CSS for my use case.

@andresfulla can you paste the custom CSS you need with this?

**Comment by andresfulla** [comment]
Yep.
```
.page-editor-toolbar-experience.dropdown-menu.toggled {
   display: block;
   max-width: 100vw;
   width: 808px;
}
```
Have in mind that this style works because I'm not using `<ClayDropdown />`, I'm using my own thing with similar markup (not creating a `React.Portal`).

`menuElementAttrs` will allow me to do this instead.

```
.dropdown-menu.toggled#my-very-special-id {
   display: block;
   max-width: 100vw;
   width: 808px;
}
```

**Comment by pat270** [comment]
@andresfulla I see. I don't think I can add support for that since it doesn't follow Bootstrap naming conventions. We can close this PR if this issue is solved.

/cc @marcoscv-work @bryceosterhaus @victorvalle

**Comment by marcoscv-work** [comment]
So we can close it! thanks a lot, @pat270 @andresfulla

**Pull request closed without merging**
