### PR TITLE
 feat(clay-css): add new change-list-disabled SVG icon

### LINKED ISSUE #2282: Please include new icon: change-list-disabled
Please find .svg file in the following ticket https://issues.liferay.com/browse/LEXI-647

### PR DESCRIPTION
**Pull request by pat270**
Fixes #2282

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
Thanks a lot @pat270.Can you see why Semantic Bot is rejecting this PR 🤷‍♂️? As soon as it's ok, we can move on.

**Comment by matuzalemsteles** [comment]
I'm going ahead with this PR, I think it might be a bug of the Semantic Bot because it passed the other PR for 2.x and this title has also been used and had passed another PR.

**Comment by wincent** [comment]
@matuzalemsteles: The thing about the Semantic Pull Requests bot on 2.x PR is that the config on the "master" branch doesn't apply there (each branch that you want to configure needs its own `.github/semantic.yml` — for example, see [the one we have on the AlloyEditor 1.x branch](https://github.com/liferay/alloy-editor/blob/1.x/.github/semantic.yml)).

So, I think the reason it didn't complain on 2.x is (probably) that that branch it doesn't have the "titleAndCommits" setting.

> By default, only the PR title OR at least one commit messsage needs to have semantic prefix. 

I guess that means that it doesn't like the backticks in the commit message, and on 2.x that was ok because it ignored the commit message and was satisfied by the PR title alone. We should probably:

1. [File an issue upstream](https://github.com/probot/semantic-pull-requests/issues).
2. Configure the bot on the 2.x branch as well (just needs a copy of the `.github/semantic.yml` file).

**Comment by wincent** [comment]
Filed upstream report [here](https://github.com/probot/semantic-pull-requests/issues/57).

**Comment by matuzalemsteles** [comment]
Thanks a lot @wincent for investigating! I'll take care later to send the copy of `.github/semantic.yml` to branch 2.x, I had forgotten about that.

**Pull request merged**
