### PR TITLE
fix(@clayui/core): Add the missing id so that the screen reader makes a correct reading

### PR DESCRIPTION
**Pull request by veroglez**
Fixes https://github.com/liferay/clay/issues/5551

### CODE REVIEW

**Review by matuzalemsteles — APPROVED** [review]
LGTM! Thanks @veroglez for catch this use case, do you have the example of the code that is falling in this use case? maybe it's rendering the wrong spacing because it's not using `component-text`.

**Comment by veroglez** [comment]
@matuzalemsteles yes, this is a use case and it seems that it's actually rendered with a wrong spacing. I have also added the `component-text` class to the `child`. Thanks for this!

Without `component-text`
wrong_spacing

With `component-text`
correct_spacing

**Comment by matuzalemsteles** [comment]
@veroglez I think the component may be using the wrong composition to not fall into the condition of being a `string`, I don't know if it's a good idea to add this to `else`, because this could be any component and we can break the implementation with that . Do you have the example of the Page Tree case that is rendered wrong?

**Comment by veroglez** [comment]
Sure! Here is the Page Tree in DXP https://github.com/liferay/liferay-portal/blob/08ccd16f507ed322a427c3d2eab3d5b7964511e3/modules/apps/product-navigation/product-navigation-product-menu-web/src/main/resources/META-INF/resources/js/PagesTree.js#L233

Screen Shot 2023-06-06 at 11 33 12 PM

Screen Shot 2023-06-06 at 11 33 28 PM

**Comment by matuzalemsteles** [comment]
I see, thanks @veroglez! It's something custom I think in this case we can avoid passing the `component-text` because we can't infer in this case what type the element is and it can cause more problems for other use cases, let's just pass the `id` in this case.

I think you can add the best class directly to your custom, for example:

```jsx
{item.regularURL ? (
  <a
    className="component-text text-truncate"
    data-tooltip-floating="true"
    href={item.regularURL}
    ref={itemAnchorRef}
    tabIndex="-1"
    target={item.target}
    title={item.name}
  >
    {item.name}
  </a>
) : item.name}
```

This simplifies the implementation a bit and removes the use of the `div` and also the second condition will go into the string case of the TreeViewItem.

**Comment by veroglez** [comment]
yes, I agree with that. Better not add the class if there are custom elements. I update the PR with the changes. On the other hand, in DXP, I will simplify the node as much as possible. Thanks for the feedback!

**Comment by matuzalemsteles** [comment]
Thanks @veroglez for that!

**Pull request merged**
