### PR TITLE
feat(@clayui/css): Add new spacers

### PR DESCRIPTION
**Pull request by marcoscv-work**
Fixes: https://github.com/liferay/clay/issues/3521

### CODE REVIEW

**Comment by pat270** [comment]
@marcoscv-work @jbalsas this adds 18kb to `atlas.css`, 2kb zipped. Are we good with that size increase? Other than that it's good with me.

**Comment by marcoscv-work** [comment]
I cry each time I see those increases but based on need from Echo team, new tokens, and their editor.. we have to :-(

**Comment by jbalsas** [comment]
Why do we have to do the spacers deep-merge twice? Is it possible we're generating more than needed?

I take that the current spacers already account for 16kb zipped... definitely not ideal, but as @marcoscv-work says... it is what it is...

**Comment by pat270** [comment]
We need `map-deep-merge` in `atlas.scss` so Sass will overwrite/replace/add to the `$spacers` map that is passed in from `_clay_variables.scss`. Then this new map will do the same to the `$spacers` map in `base.scss`. This is preferred so the user doesn't need to redeclare all the key value pairs when modifying a map.

We might be generating more than needed, but it's not from `map-deep-merge`. We are generating `margin` and `padding` utilities for every breakpoint with and without `!important`.

```
  .c-m-sm-10 {
    margin: 10rem;
  }
  .c-mt-sm-10,
  .c-my-sm-10 {
    margin-top: 10rem;
  }
  .c-mr-sm-10,
  .c-mx-sm-10 {
    margin-right: 10rem;
  }
  .c-mb-sm-10,
  .c-my-sm-10 {
    margin-bottom: 10rem;
  }
  .c-ml-sm-10,
  .c-mx-sm-10 {
    margin-left: 10rem;
  }
```

**Pull request merged**
