### PR TITLE
Fixes #1250 - ClayCreationMenuDropdown should accept empty array or undefined primaryItems 

### LINKED ISSUE #1250: ClayCreationMenuDropdown should accept empty array or undefined primaryItems

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
Hey guys, are we in trouble with Travis?

**Comment by julien** [comment]
@matuzalemsteles I had issues until last night but everything seems to be back to normal now.

**Comment by matuzalemsteles** [comment]
Thanks @julien, I was finding it strange because I was not seeing the CI checks here on github.

**Comment by matuzalemsteles** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by julien** [comment]
No problem @matuzalemsteles, just so you know I had to restart the build several times from travis.

**Pull request merged**
