### PR TITLE
Revert #1634 - Headers size

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
This is only for 2.x-develop branch

**Comment by matuzalemsteles** [comment]
hey @marcoscv-work, why are we just keeping on 2.x? will we release the clay-css for 3.x as well?

**Comment by marcoscv-work** [comment]
> hey @marcoscv-work, why are we just keeping on 2.x? will we release the clay-css for 3.x as well?

Hey @matuzalemsteles we want this change but right now in liferay portal we cannot solve some issues related with this change, so we can keep it in 3.x and revert it for 2.x. in this way we will not loss the change

**Comment by matuzalemsteles** [comment]
Oh okay. Thanks @marcoscv-work for the info.

**Pull request merged**
