### PR TITLE
Adding colon to alert titles.

### LINKED ISSUE #1348: Alert titles don't follow lexicon spec
They should be followed by a ":". See https://issues.liferay.com/browse/LPS-87793.

### PR DESCRIPTION
**Pull request by 4lejandrito**
Fixes #1348 See https://lexicondesign.io/docs/patterns/alerts.html

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
hey @4lejandrito, Thanks for this, can you regenerate the expected fixtures too?

**Comment by matuzalemsteles** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matuzalemsteles** [comment]
I took care of this for you, I'm sending it on #1353.

**Comment by 4lejandrito** [comment]
Thanks @matuzalemsteles!

**Pull request closed without merging**
