### PR TITLE
chore(release): publish v3.35.3 packages

### PR DESCRIPTION
**Pull request by julien**
This is me just testing the steps described in 
the [release process](https://github.com/liferay/clay/blob/2697c1e53795b15e58240d863417d63811f5e5dd/CONTRIBUTING.md#release-process), so I'll make this a draft, but I still would 
like to see it pass. 

@matuzalemsteles, @bryceosterhaus if you have time 
and see anything fishy, let me know. Thanks

### CODE REVIEW

**Comment by julien** [comment]
Well that failed quickly.
I've got a feeling that this error from the (CI/test) job:

```
  @clayui/provider:  BAD
    clay-core -> ^3.35.3
    clay-shared -> ^3.35.2
```

is something that needs to fixed manually.
Running `yarn checkDeps` in the `master` branch
also fails but with other errors.

```
Add missing dependencies with:

(cd packages/clay-core && yarn add @storybook/react classnames react-dnd react-dnd-html5-backend @clayui/shared react-transition-group @clayui/layout)
```

**Comment by bryceosterhaus** [comment]
Okay I just got a chance to check this out.

```
 @clayui/provider:  BAD
    clay-core -> ^3.35.3
    clay-shared -> ^3.35.2
```

At first I was confused by this, but then I realized I was reading it wrong. This error is saying

"The `@clayui/provider` dependency is declared in clay-core as `^3.35.3` and in clay-shared as `^3.35.2`".

Meaning, these versions are out of sync.

If you bump the peerDependency in clay-shared so that it is dependent on `^3.35.3`, that problem should be solved.

As for running `yarn checkDeps` locally, you need to also make sure that you clean your built `lib` folders. I suspect that you have old built files since they are untracked by git. `checkDeps` is based on the built files and not the source files. It may be worthwhile to add a `clean` type of script to checkDeps so that we make sure the lib folders are wiped.

**Comment by julien** [comment]
@bryceosterhaus thanks for the help and time.

Concerning the first error, you were right I did have to bump manually, 
which is why you'll see [this](https://github.com/liferay/clay/pull/4256/commits/446a10569e34c162ec169b227f3eac6ab07b416c) commit, (we can talk about it this is 
still a "test pr for myself" but this might be needed).

Everything else concerning the release process went fine.

Before running `yarn checkDeps` locally, I used 

```sh
find packages/ -mindepth 2 -maxdepth 2 -name lib -type d | xargs rm -rf {}
```

Which worked fine for me (and that we could use), but since I'm 
not on macOS I'll also ask @matuzalemsteles to try
that on his machine, because I'd just like to be sure that works 
for him too (and I've had issues with xargs on mac in the past).

Anyway, even if I'm going to delete this branch in a bit, 
I'd still like to keep it open for us to discuss.

**Comment by matuzalemsteles** [comment]
@julien yeah, unfortunately as `@clayui/provider` is a peerDependency we have to manually update in `@clayui/shared`, I wanted to try to get rid of it but the circular dependency is very difficult to avoid, even if I put the files in `shared` we will have circular dependency due to the dependencies of the `provider` 😭. I hope I can remove this with the issue #4191 entry.

> Which worked fine for me (and that we could use), but since I'm not on macOS [...]

Yeah that worked fine on my machine I think it would be safe to add that. I'm not sure if we should add this to a script, maybe just as part of the release process.

**Comment by julien** [comment]
> Which worked fine for me (and that we could use), but since I'm not on macOS [...]

> Yeah that worked fine on my machine I think it would be safe to add that. I'm not sure if we should add this to a script, maybe just as part of the release process.

Great, thanks for notifying. I think I can edit the release process document to include that - it's a very simple command so I agree that we don't need a script (or npm script) for that either

**Comment by julien** [comment]
Closing this, since it was a "test run" pull request :) Thanks for the help guys.

**Pull request closed without merging**
