### PR TITLE
feat(clay-css): SVG Icons adds shield-check

### LINKED ISSUE #3755: Please add shield-check icon
Hi!

We have [this request](https://issues.liferay.com/browse/LEXI-1055) for creating an icon.

Please find the icon attached.
Name: shield-check

**The priority is major** for this issue, as stated in the ticket requested to us.

Thanks in advance!

### PR DESCRIPTION
**Pull request by pat270**
fixes #3755

### CODE REVIEW

**Review by matuzalemsteles — APPROVED** [review]
LGTM! Do we need to add this icon for 2.x as well? Netlify builds are failing but they shouldn't be activated for this branch. @bryceosterhaus can you take care of the disable this? I don't have access to the Netlify account.

**Comment by pat270** [comment]
Hey @matuzalemsteles This pr is for 2.x. The one for 3.x got merged already.

**Comment by matuzalemsteles** [comment]
@pat270 sorry, I think I ended up asking the wrong question, what I wanted to say is, do we need this to go into 2.x? because I think we’d only have to send this to 7.2 or 7.1 if I’m not mistaken. Since 7.3 is using the @clayui/css 3.x package

**Comment by pat270** [comment]
@matuzalemsteles ah yes, they want to use it for 7.1 and 7.2.

**Comment by bryceosterhaus** [comment]
@matuzalemsteles I'm not sure why its building previews for this branch. Its configured to only build for `master`...

**Comment by matuzalemsteles** [comment]
@pat270 ok, we can move on. @bryceosterhaus hmm no problems.

**Comment by marcoscv-work** [comment]
Hi guys, @pat270 @mateomustapic The PR hasn't merged yet, is this intentional?

**Comment by matuzalemsteles** [comment]
@marcoscv-work it wasn't really intentional, I'm going to merge that.

**Pull request merged**
