### PR TITLE
fix(clay-data-provider): remove metal-uri dependency in favor of URL

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Since we have a [polyfill for searchParams](https://github.com/liferay/liferay-portal/blob/b628b3a178accd00caa4908222c1a122f8b539df/modules/apps/frontend-compatibility/frontend-compatibility-ie/build.gradle#L293-L307) in portal, can we can just use URL instead?

cc: @jbalsas

### CODE REVIEW

**Comment by jbalsas** [comment]
We have `URLSearchParams` polyfill, but not `URL`, which is also not supported in IE11. I think that makes no difference though.

I'd say let's go with this and we can add both `URL` and `URLSearchParams` to Liferay Portal for IE11 only, maybe via https://github.com/lifaon74/url-polyfill.

/cc @wincent, @julien?

**Comment by bryceosterhaus** [comment]
@jbalsas oh my bad, I had only looked at `URLSearchParams` which is the `searchParams` of URL, but I wasn't aware that even URL isn't support. Need to do my research next time...

**Comment by wincent** [comment]
> I'd say let's go with this and we can add both `URL` and `URLSearchParams` to Liferay Portal for IE11 only, maybe via https://github.com/lifaon74/url-polyfill.

For reference, the main ticket we have covering expanding our polyfill coverage in IE11 is this one: https://issues.liferay.com/browse/LPS-95425

I'll add a link back here from there.

**Comment by matuzalemsteles** [comment]
hey guys, from what I'm seeing from this discussion, this sounds good, so I'm going ahead with this PR.

**Comment by kresimir-coko** [comment]
If this has been merged does it mean I can use `new URL()` in my utils that I'm modernizing, for example https://github.com/markocikos/liferay-portal/pull/112

**Comment by wincent** [comment]
> If this has been merged does it mean I can use `new URL()` in my utils that I'm modernizing

Just to reflect that parallel discussion that we had on Slack about this, technically, we shouldn't ship anything to liferay-portal that relies on `URL` until the polyfilling for IE is done (it hasn't been yet).

**Pull request merged**
