### PR TITLE
fix(@clayui/css): Removes unused variables

### LINKED ISSUE #4230: @clayui/css Remove duplicate and unused variables
There are duplicate and unused variables in several places.

```scss
$dropdown-font-size // appears twice in Base theme
$input-height-inner-lg // only in atlas
$input-height-inner-sm // only in atlas
$custom-control-indicator-checked-border-color // appears twice in base theme
$custom-control-description-disabled-color // only in atlas
$timeline-increment-label-color // only in atlas
```

### PR DESCRIPTION
**Pull request by pat270**
fixes #4230

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
Hey @pat270 does that mean we only had those variables declared but change them wouldn't change anything?

**Comment by pat270** [comment]
@matuzalemsteles Yes, declared but not used in our functions, mixins, or component scss. The `input-height-inner-*` variables Bootstrap removed between [4.2.1](https://github.com/twbs/bootstrap/blob/9e4e94747bd698f4f61d48ed54c9c6d4d199bd32/scss/_variables.scss#L492) and [4.3.0](https://github.com/twbs/bootstrap/blob/1ded0d6a4eefb7daca62c44e4e735aec200f0b6f/scss/_variables.scss#L492). `input-height-inner-*-mobile` we added to follow Bootstrap's pattern.

**Comment by matuzalemsteles** [comment]
Oh thanks @pat270 for the information.

**Review by matuzalemsteles — APPROVED** [review]
LGTM

**Pull request merged**
