### PR TITLE
fix(@clayui/css): SVG Icons bookmarks and bookmarks-full should be centered

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPS-199263

@matuzalemsteles I grabbed the icons from the Lexicon Icon library on Figma. They use `viewBox="0 0 16 16"`. I remember we had issues when the viewBox wasn't `viewBox="0 0 512 512"`. I don't remember if it was because of Clay or a tag in DXP. I was hoping you remember.

/cc @drakonux @emiliano-cicero

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
I'm not sure if this is specifically a problem with the viewport, it could perhaps be a problem with the generated svg that may be off-center within the 512x512 viewport because we have other icons similar to this.

**Comment by pat270** [comment]
@matuzalemsteles In the `<clay:icon>` tag we are hardcoding the `viewBox`.

https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/IconTag.java#L31

Should we swap out all the SVG's to use the `0 0 16 16` from the Lexicon Icon library?

https://github.com/liferay/clay/issues/4763

**Comment by matuzalemsteles** [comment]
@pat270 I'm not sure about this and I don't think this is the problem yet, my assumption is that the misalignment is the problem with the icon not being positioned correctly within the 512x512 viewport, I would check this first before proceeding with 16x16.

**Comment by pedro-michel** [comment]
I believe this is the same problem that we had in last days with X & Canada Flag icon, right @pat270 ?

**Pull request merged**
