### PR TITLE
Fix(next.clayui.com): (#2126) Page visual simplification

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, merging this so we can start playing around with the proposal @marcoscv-work and @eduardoallegrini want to do on simplification.

I remember you mentioned we were creating different pages for the site pull requests... is that the case? can we see the results of site PRs without merging them or building them locally?

**Comment by jbalsas** [comment]
Actually, `CI` is not green. @marcoscv-work, please see and fix before we merge:

```
next.clayui.com/src/components/Sidebar/Sidebar.js
success formatting 1 file with prettier-eslint
230 files were unchanged
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ prettier: `prettier-eslint '**/*.{js,ts,tsx}' "--list-different"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ prettier script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-06-26T23_01_59_557Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "yarn run checkFormat" exited with 1.
```

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Pull request submitted to https://github.com/liferay/clay/pull/2132. [See changes here.](https://github.com/liferay/clay/compare/7d8614ce9~5...7d8614ce9) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
