### PR TITLE
feat(@clayui/drop-down): add more options for alignment

### LINKED ISSUE #2909: ClayDropdown positions
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?
No =(

## What are the steps to reproduce?
The position TopLeft TopRight is not supported, passing it through props works, but without offset as a side effect.

## What is the expected result?
It will be great an API to define offset, and also support to this position if possible.

## Environment

| Tech  | Version |
| ClayDropdown  | v3.1.3  |
| React |   v16.8.6      |

### PR DESCRIPTION
**Pull request by bryceosterhaus**
fixes #2909

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
@fcodias can you verify this is what your expectations are? Check out the storybook to see the example, https://deploy-preview-2924--storybook-clayui.netlify.com/

**Comment by fcodias** [comment]
Thanks @bryceosterhaus , it looks good!! I think it's ok for our case. 
About the offset, do you think it will be possible to define it?

**Comment by matuzalemsteles** [comment]
Looks good to me! Before going with that maybe we could implement an API for `offset` (as mentioned by @fcodias).

**Comment by bryceosterhaus** [comment]
@fcodias @matuzalemsteles added a new commit with custom offset functionality. Let me know if that looks like what you'd expect

**Comment by fcodias** [comment]
Looks nice @bryceosterhaus! Thank you very much!!

**Pull request merged**
