### PR TITLE
fix(@clayui/form): pressing enter on label with focus should remove

### PR DESCRIPTION
**Pull request by matuzalemsteles**
This is related to #2376

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
Yeah, I think it follows the same idea that when pressing backspace the focus will go to the whole label and when pressing again removes it. @drakonux can confirm this for us.

**Comment by bryceosterhaus** [comment]
Yeah my concern was that if the focus is on the label, that doesn't communicate to screen readers that hitting backspace would cause it to delete. I was under the impression that interactive elements need to be buttons/links/inputs. I would think that the `enter` keypress functionality would need to focus the "close" button and not the label.

**Comment by drakonux** [comment]
Hi guys!

Well talking offline with @marcoscv-work this morning about https://github.com/liferay/clay/pull/2376 . We agreed that we shouldn't make assumptions about how to manage the focus when a user removes a label. So when the user clicks or press remove button the focus is not located on the next label or the input. 

Simply, if the user press tab key **again**. The focus will be located on the next remove button or input (if the label removed was the last)

**Comment by matuzalemsteles** [comment]
Thanks @drakonux, can we document this? I'm following old behaviors here so that when we release Clay we don't have behavioral regressions.

> Simply, if the user press tab key again. The focus will be located on the next remove button or input (if the label removed was the last)

I don't know if this goes against what you said above, not controlling behavior when removing, since we do that we will let the browser behavior decide.

**Comment by drakonux** [comment]
Yeah no problem. As I said, If you need something create a request in Lexicon because this is an intensive work for me (remember that none of the designers that wrote the old documentation is still in Lexicon). 

> I don't know if this goes against what you said above, not controlling behavior when removing, since we do that we will let the browser behavior decide.

I'm sorry. Finally, if you read the last comment from @marcoscv-work in [2376](https://github.com/liferay/clay/issues/2376) we agreed the behavior in that ticket because talking with Chema is the best option to implement for now (and solve most of the questions/doubts we had).

**Pull request closed without merging**
