### PR TITLE
Adds tslint.json to the root folder for Codacy

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
hey @jbalsas any updates on this? Can we go with this like this?

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, I've disabled the `clayui.com` folder from `Codacy`. I'm still seeing the errors, but it might be just a fluke.

Looks like there are some conflicts here with our latest changes on the site... could you resend on top of `develop` so we can merge this in?

Thanks!

**Comment by matuzalemsteles** [comment]
Thanks @jbalsas, I will resolve the conflicts and resent. Will we keep `tslint.json` at the root?

**Comment by jbalsas** [comment]
Nah, feel free to remove it as we hopefully won't need to fix that

**Pull request closed without merging**
