### PR TITLE
Clayui.com adds theme toggle

### PR DESCRIPTION
**Pull request by pat270**
There's probably a more elegant way to do this, but I don't know react.

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Hey @pat270 
Why do we need to add this control? do you want it for development reasons?
If we really need to switch atlas/base, could we use a mechanism only visible for us?

**Comment by pat270** [comment]
@marcoscv-work I would say because a lot of our customers base their theme on Styled instead of Classic? I remember seeing something about extending Classic Theme not being supported by our tools.

**Comment by marcoscv-work** [comment]
Hey guys, sorry for the delay..

I suppose people in USA is asking for this, is it right @pat270 ?
My only concern is where should we place this control to switch base/atlas
I this is a strategic decision too, so @jbalsas could you help us to make a decision?

**Pull request closed without merging**
