### PR TITLE
fix: updates copyright headers to appropriate year

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Stems from https://github.com/liferay/clay/pull/3711#discussion_r493367143

### CODE REVIEW

**Comment by pat270** [comment]
Copy pasting from other pr that was merged, we should leave the copyright year alone.

> How to write a good copyright statement and license notice
the year of the first publication – a good date would be the year in which you created the file and then do not touch it anymore;

Reference: https://liferay.dev/blogs/-/blogs/how-and-why-to-properly-write-copyright-statements-in-your-code#how-to-write-a-good-copyright-statement-and-license-notice

**Review by wincent — CHANGES_REQUESTED** [review]
Requesting changes to prevent accidental merge. I agree with @pat270. My fireside chats with our legal folk lead me to share his understanding that we aren't supposed to update the year.

**Comment by jbalsas** [comment]
> My fireside chats with our legal folk lead me to share his understanding that we aren't supposed to update the year.

I even seem to recall some conversation mentioning the option to skip it altogehter?

**Comment by wincent** [comment]
> I even seem to recall some conversation mentioning the option to skip it altogehter?

Yes, but that's Matija talking about he would _like_ the world to be, not how the world _is_. [This internal doc](https://grow.liferay.com/people?p_p_id=com_liferay_wiki_web_portlet_WikiPortlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&_com_liferay_wiki_web_portlet_WikiPortlet_struts_action=%2Fwiki%2Fview&_com_liferay_wiki_web_portlet_WikiPortlet_redirect=%2Fpeople%3Fq%3Doutbound%2520licensing%2520&_com_liferay_wiki_web_portlet_WikiPortlet_pageResourcePrimKey=1574973&p_r_p_http%3A%2F%2Fwww.liferay.com%2Fpublic-render-parameters%2Fwiki_nodeName=Grow&p_r_p_http%3A%2F%2Fwww.liferay.com%2Fpublic-render-parameters%2Fwiki_title=Liferay+Outbound+Licensing+Policy) provides the guidance on the _current_ policy:

> `{year_of_creation}` with the year when this file was first created/published and therefore the year from when it started being protected by copyright (yes, no more annual bumping of the year!);

**Comment by jbalsas** [comment]
> Yes, but that's Matija talking about he would like the world to be, not how the world is. This internal doc provides the guidance on the current policy:

Got it! I didn't know if that ever became reality. Sad it hasn't :(

**Comment by wincent** [comment]
> Got it! I didn't know if that ever became reality. Sad it hasn't :(

I think he's trying to get these desired changes into the REUSE software guidelines, and then apply the changes to our projects (probably changing our projects first, because that is easier than changing DXP itself, so we'll be among the first to know).

**Comment by bryceosterhaus** [comment]
> we aren't supposed to update the year.

Good to know! I'll go ahead and close

**Pull request closed without merging**
