### PR TITLE
Fixes #1333 Lock event stream to 3.3.4

### LINKED ISSUE #1333: Malware in a dependency
Clay has a transitive dependency through 'event-stream' to a node-module called 'flatmap-stream'.

The version of 'event-stream' that is effected is 3.3.6.

You should lock the version to 3.3.4 until 3.3.7 is released, or upgrade to 4.0.

The malware searches a user's computer for Bitcoin wallets and empties them.

https://github.com/dominictarr/event-stream/issues/115

### PR DESCRIPTION
**Pull request by sbaechler**
Revert event-stream to 3.3.4.
#1333

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matuzalemsteles** [comment]
hey @sbaechler, Can you make a rebase over the branch develop? thanks!

**Comment by sbaechler** [comment]
@matuzalemsteles This is a security issue and should be added ASAP.

**Comment by matuzalemsteles** [comment]
hey @sbaechler I understand, but we have to keep up the standards so this does not turn into a mess.

Resent #1335

**Pull request closed without merging**
