### PR TITLE
fix(@clayui/css): SVG Icons updates `align-image-center`, `align-image-left`, and `align-image-right` with rounded borders

### LINKED ISSUE #3432: Update icons: align-image  icons
Due to [LEXI-979](https://issues.liferay.com/browse/LEXI-979). Lexicon has updated the image alignment icons:

- _align-image-left_
- _align-image-center_
- _align-image-right_

image-alignment-icons

Please update these icons. Find the SVG's on the ticket.
Thanks!

### PR DESCRIPTION
**Pull request by pat270**
fixes #3432

### CODE REVIEW

**Comment by wincent** [comment]
(Non-blocking feedback... just wanting to point out the difference)

Rebasing and force-pushing would result in a cleaner history. 

ie:

```
* 8a907487f (HEAD -> pull/3440) docs(clayui.com): Adds aliases for `align-image-center`, `align-image-left`, and `align-image-right` (10 seconds ago) <Patrick Yeo>
* c3ae588b3 fix(@clayui/css): SVG Icons updates `align-image-center`, `align-image-left`, and `align-image-right` with rounded borders (82 seconds ago) <Patrick Yeo>
* 34443361b (upstream/master, upstream/HEAD, master) Merge pull request #3455 from kresimir-coko/3454 (2 hours ago) <Greg Hurrell>
```

instead of:

```
*   da113090f (HEAD -> pull/3440) Merge branch 'master' into clay-3432 (12 minutes ago) <Marcos Castro>
|\
| *   34443361b (upstream/master, upstream/HEAD, master) Merge pull request #3455 from kresimir-coko/3454 (2 hours ago) <Greg Hurrell>
| |\
| | * e90068eba feat(clayui.com): Add JSP code example to Label (3 hours ago) <Krešimir Čoko>
| |/
| *   e495fc8c6 Merge pull request #3419 from diegonvs/3374 (3 days ago) <Matuzalém Teles>
| |\
| | * 587c3e474 fix(@clayui/date-picker): Fix conditional (3 days ago) <Diego Nascimento>
| | * 8b99c3c22 fix(@clayui/date-picker): For old browsers, `Spacebar`, for the new ones, `' '` (4 days ago) <Diego Nascimento>
| | * 64af3da7b fix(@clayui/date-picker): Use `Spacebar` value for validating if the correct key of the KeyboardEvent was triggered (4 days ago) <Diego Nascimento>
| | * 8259f5887 fix(@clayui/date-picker): Remove unecessary onKeyDown and onKeyUp callbacks since DayNumber is a private component (4 days ago) <Diego Nascimento>
| | * e429ede8f chore(@clayui/date-picker): Replace .keyCode with .key for handling key detection (4 days ago) <Diego Nascimento>
| | * 7b0550d34 chore(@clayui/date-picker): Prefer destructuring (5 days ago) <Diego Nascimento>
| | * e098b1fbe fix(@clayui/date-picker): When selecting a date using space key, removes properly the `:active` state of the element (5 days ago) <Diego Nascimento>
| * |   eff1809ab Merge pull request #3452 from kresimir-coko/3444 (3 days ago) <Greg Hurrell>
| |\ \
| | * | 843f1a008 feat(clayui.com): Add JSP code example to Button (3 days ago) <Krešimir Čoko>
| |/ /
| * |   ad80a5733 Merge pull request #3446 from kresimir-coko/3444 (3 days ago) <Greg Hurrell>
| |\ \
| | * | fd49a248d feat(clayui.com): Add JSP code example to Button (3 days ago) <Krešimir Čoko>
| * | |   1671b4e37 Merge pull request #3443 from pat270/clay-3435 (3 days ago) <Greg Hurrell>
| |\ \ \
| | * | | e4dd3b693 docs(clayui.com): Adds alias for copy icon (3 days ago) <Patrick Yeo>
| | * | | cdd96ab28 feat(@clayui/css): SVG Icons changes `paste` to something more relevant and moves original `paste` to `copy` (3 days ago) <Patrick Yeo>
| | |/ /
| * | |   270d7c588 Merge pull request #3442 from pat270/clay-3434 (3 days ago) <Greg Hurrell>
| |\ \ \
| | * | | 1db4f98d3 feat(@clayui/css): SVG Icons adds `select-all` (3 days ago) <Patrick Yeo>
| | |/ /
| * | |   87cedfa95 Merge pull request #3441 from pat270/clay-3433 (3 days ago) <Greg Hurrell>
| |\ \ \
| | * | | 5abf086ef docs(clayui.com): Adds alias for `background-color` icon (3 days ago) <Patrick Yeo>
| | * | | 7ae36346f feat(@clayui/css): SVG Icons adds `background-color` (3 days ago) <Patrick Yeo>
| | |/ /
| * | |   721013b7e Merge pull request #3439 from pat270/clay-3431 (3 days ago) <Greg Hurrell>
| |\ \ \
| | * | | 0a4d29061 docs(clayui.com): Adds alias for align-image-full-width SVG icon (3 days ago) <Patrick Yeo>
| | * | | 26db99e42 feat(@clayui/css): SVG Icons adds `align-image-full-width` (3 days ago) <Patrick Yeo>
| | |/ /
| * | |   bea612725 Merge pull request #3438 from pat270/c-3149-the-rest (3 days ago) <Greg Hurrell>
| |\ \ \
| | |/ /
| |/| |
| | * | 8c7c71f1d fix(@clayui/css): Badges Variables forgot to remove some commented code (4 days ago) <Patrick Yeo>
| | * | 9c21b3372 fix(@clayui/css): Completed absorbtion of Bootstrap 4 components, moves all imports from _bs4.scss to _components.scss (4 days ago) <Patrick Yeo>
| | * | 1c3ace2be revert(@clayui/css): Mixins `clay-link` `disabled` should set `outline: 0` and `box-shadow: none` by default so disabled anchors don't receive focus outline (4 days ago) <Patrick Yeo>
| | * | 5b1fb4dd3 feat(@clayui/css): Absorb Bootstrap's _navbar.scss into Clay CSS _navbar.scss (4 days ago) <Patrick Yeo>
| | * | e802d1f10 feat(@clayui/css): Absorb Bootstrap's _btn-group.scss into Clay CSS _btn-group.scss (4 days ago) <Patrick Yeo>
| | * | b704e7fbe feat(@clayui/css): Button adds placeholders `%clay-btn-monospaced-lg`, `%clay-btn-monospaced-sm` so we can extend with Sass `@extend` without unnecessary selectors (4 days ago) <Patrick Yeo>
| | * | b1b7adb70 feat(@clayui/css): Absorb Bootstrap's _utilities.scss into Clay CSS _utilities-functional-important.scss (4 days ago) <Patrick Yeo>
| | * | a00ec52b0 feat(@clayui/css): Absorb Bootstrap's _spinners.scss into Clay CSS _spinners.scss (4 days ago) <Patrick Yeo>
| | * | 8d4334424 feat(@clayui/css): Absorb Bootstrap's _popover.scss into Clay CSS _popovers.scss (4 days ago) <Patrick Yeo>
| | * | c2a4de8e2 feat(@clayui/css): Absorb Bootstrap's _modal.scss into Clay CSS _modals.scss (4 days ago) <Patrick Yeo>
| | * | c3026d530 feat(@clayui/css): Absorb Bootstrap's _close.scss into Clay CSS _utilities.scss (4 days ago) <Patrick Yeo>
| | * | 8318d9f67 feat(@clayui/css): Mixins `clay-close` removes Bootstrap 4.1.2 selector overwrites. We don't need them since we are removing Bootstrap 4 dependency. (4 days ago) <Patrick Yeo>
| | * | a685d6b9a feat(@clayui/css): Absorb Bootstrap 4 _media.scss into Clay CSS _media.scss (4 days ago) <Patrick Yeo>
| | * | 086979732 feat(@clayui/css): Absorb Bootstrap's _alert.scss into Clay CSS _alerts.scss (4 days ago) <Patrick Yeo>
| | * | cfe46c7ea feat(@clayui/css): Absorb Bootstrap's _badge.scss into Clay CSS _badges.scss (4 days ago) <Patrick Yeo>
| | * | 39fc48f4c fix(@clayui/css): Remove unused import `@import 'bootstrap/breadcrumb'` (4 days ago) <Patrick Yeo>
| | * | f9215a9ff chore(clay-css-test-site): Breadcrumbs add example not using ul or ol (4 days ago) <Patrick Yeo>
| | * | 9d30cab87 feat(@clayui/css): Absorb Bootstrap's _breadcrumb.scss into Clay CSS _breadcrumbs.scss (4 days ago) <Patrick Yeo>
| | * | 52cd5f824 feat(@clayui/css): Absorb Bootstrap 4 _custom-forms.scss into Clay CSS _custom-forms.scss (4 days ago) <Patrick Yeo>
| |/ /
* | | 36ff87da2 docs(clayui.com): Adds aliases for `align-image-center`, `align-image-left`, and `align-image-right` (3 days ago) <Patrick Yeo>
* | | 83ce2918d fix(@clayui/css): SVG Icons updates `align-image-center`, `align-image-left`, and `align-image-right` with rounded borders (3 days ago) <Patrick Yeo>
|/ /
* |   1c3b17d86 etc...
```

(Will look slightly worse that than once this one gets merged, because you'll *also* get the merge back into `master`).

**Comment by marcoscv-work** [comment]
Oh, I see. I used the git interface to edit the files and save.
Do we need to go back?

**Comment by wincent** [comment]
> Oh, I see. I used the git interface to edit the files and save.
> Do we need to go back?

No, I don't think you need to go back unless you want to. A clean history is good, but I don't want to create additional work for anybody.

I do notice that we resolved the conflict in a different way though, so I pushed mine up here for comparison: https://github.com/liferay/clay/pull/3458 — I did it in a rush (I only wanted to demo the shape of the commit graph), so there's a reasonable chance that I did it wrong, but I'll take a closer look and leave a comment over there describing my conclusion.

**Comment by marcoscv-work** [comment]
> > Oh, I see. I used the git interface to edit the files and save.
> > Do we need to go back?
> 
> No, I don't think you need to go back unless you want to. A clean history is good, but I don't want to create additional work for anybody.
> 
> I do notice that we resolved the conflict in a different way though, so I pushed mine up here for comparison: #3458 — I did it in a rush (I only wanted to demo the shape of the commit graph), so there's a reasonable chance that I did it wrong, but I'll take a closer look and leave a comment over there describing my conclusion.

Awesome, so we can close this PR, right?

**Comment by wincent** [comment]
> Awesome, so we can close this PR, right?

Let's just double check everything first (I'm looking at it now) to make sure we close the "right" one.

**Comment by wincent** [comment]
See [this comment](https://github.com/liferay/clay/pull/3458#issuecomment-654214528). I think I see one cosmetic difference (alpha ordering, no big deal) and one actual problem (this PR has duplicate `align-image-left` entries).

**Comment by wincent** [comment]
To prevent an accidental merge, going to close this one.

**Pull request closed without merging**
