### PR TITLE
feat(@clayui/css): Adds focus-within

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPS-195104

This adds `:focus-within` to our `form-control` elements. This offloads focus interactions to the browser on more complex elements like `input-group`s (e.g., search bar, time picker, rgb inputs in color picker).  We weren't managing the focus class on a lot of input groups and now we no longer need to.

~One thing I don't like is the name of the `form-control-container` class. I was hoping for something better, but can't think of anything. @matuzalemsteles @ethib137 do you think we should add an attribute to the `ClayInput.GroupItem` component to output this? I'm currently adding it via `className="form-control-container"`.~

Edit: Went with `input-group-item-focusable`. Thanks @ethib137 !

### CODE REVIEW

**Comment by ethib137** [comment]
Hey @pat270 can you make sure to get a design review of these changes to how focus is displayed before this is merged.

**Comment by marcoscv-work** [comment]
Should be these the url to test this PR?
https://deploy-preview-5670--next-clayui.netlify.app/docs/components/dual-list-box.html
https://deploy-preview-5670--next-storybook-clayui.netlify.app/?path=/story/design-system-components-duallistbox--default

**Comment by pat270** [comment]
@marcoscv-work yes, that url contains the changes here.

**Comment by matuzalemsteles** [comment]
Well, if we want this automatically, we can add this class directly to `ClayInput.GroupItem. But maybe we don't want this for all cases, for example in the Search case, does it make sense to show the focus on the input when the focus is on the search button? This seems confusing to the user.

**Comment by pat270** [comment]
@matuzalemsteles The focus shouldn't be on the input when the search button is focused. I need to update the selector to account for that. I remember thinking about excluding `input[type="submit"]`, but couldn't think of a use case.

**Comment by pat270** [comment]
@matuzalemsteles where are you seeing the search button focus issue?

**Comment by matuzalemsteles** [comment]
@pat270 No, I ended up misunderstanding.

**Comment by pat270** [comment]
There is an issue, but it's only with `<input type="submit" value="Submit"/>`. These aren't generally used in input groups since it's hard to swap out an icon for text. We can use `<button type="submit">` for that.

**Comment by pat270** [comment]
@matuzalemsteles I'm still thinking about the class name, can you ping me before merging it. I can't find how to convert to draft for some reason.

**Comment by matuzalemsteles** [comment]
@pat270 Of course, I think that after the PR is ready, it is not possible to go back to draft again, just draft > ready.

**Pull request merged**
