### PR TITLE
 Fixes #1713 - Removes the use of text inside the Sticker in case of using the User Card

### LINKED ISSUE #1713: User Card Update
https://issues.liferay.com/browse/LEXI-503

We need to update the user card to avoid text inside the sticker. 

1. Stickers shouldn't allow text in order to improve accessibility and language changes.
2. As in the latest documentation update the sticker size should go from a minimum size of 48px to a maximum size of 80px.
3. Use the User Icon inside the sticker a a placeholder when the User Image is not provided.

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
Depends on #1715

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Merged, thx!

**Pull request merged**
