### PR TITLE
feat(@clayui/css): LPD-39299 Adds d4-l1 for colors

### PR DESCRIPTION
**Pull request by pat270**
https://liferay.atlassian.net/browse/LPD-39299

This needs to make it into DXP before we can merge https://github.com/liferay-platform-experience/liferay-portal/pull/753

### CODE REVIEW

**Comment by ethib137** [comment]
LGTM... just one question... If we are using the same value for atlas and default variables do we have to duplicate it? Instead can we just leave out the variables from atlas? I'm guessing you are adding the variables to atlas because this is an existing pattern, but I just wanted to check. Thanks.

**Review by matuzalemsteles — APPROVED** [review]
LGTM!

**Comment by ethib137** [comment]
@matuzalemsteles Let's make sure this is in the early release as well.

**Comment by pat270** [comment]
@ethib137 yeah we can leave it out from atlas. I duplicate it because it's much easier to copy and paste global variables for developers wanting to extend Atlas theme.

**Comment by ethib137** [comment]
No problem, if thats our existing pattern then thats fine. thanks

**Pull request merged**
