### PR TITLE
chore(clayui.com): adds DropDownWithDrilldown component doc

### LINKED ISSUE #3707: Add ClayDropDownWithDrilldown component documentation on clayui.com
The DropDown implementation with Drilldrown was recently implemented but we have not yet added documentation.

### PR DESCRIPTION
**Pull request by matuzalemsteles**
Fixes #3707

### CODE REVIEW

**Comment by kresimir-coko** [comment]
Hey @matuzalemsteles not sure if this is a deploy preview bug, or on your end, but here's how the API table looks for DropDownWithDrilldown in the deploy preview:
image

**Comment by matuzalemsteles** [comment]
> Hey @matuzalemsteles not sure if this is a deploy preview bug, or on your end, but here's how the API table looks for DropDownWithDrilldown in the deploy preview:

😱 thanks for catching this, I think it only worked in the development environment, I'll check. Thanks @kresimir-coko

**Comment by matuzalemsteles** [comment]
I can't figure out the cause, it's working well in the development and production environment locally I'm assuming it may have been a build failure. @bryceosterhaus can you run the build again of this PR on Netlify? I'm without access.

**Review by bryceosterhaus — APPROVED** [review]
LGTM!

**Comment by matuzalemsteles** [comment]
Okay, I will go ahead with this PR and check if the final build of next.clayui.com came out with the expected result from the API, otherwise, I will investigate it and send it in another PR.

**Pull request merged**
