### PR TITLE
feat(@clayui/css): Absorb Bootstrap 4 _images.scss

### PR DESCRIPTION
**Pull request by pat270**
issue #3149

### CODE REVIEW

**Comment by jbalsas** [comment]
I'm still uneasy with this. Seeing as we're going down this path, can someone please file an LRIT inbound licensing to discuss the proper way to bring this in? 

@silverhook should be able to help clarify the right way to do this.

**Comment by carmenbianca** [comment]
Not sure if there's a ticket elsewhere for this. This doesn't seem especially difficult. @silverhook should know the ins and outs, but given that Bootstrap is [licensed under MIT](https://getbootstrap.com/docs/4.0/about/license/), the only requirement is that Bootstrap's copyright notice be preserved.

The steps to do that are:

1. Include [Bootstrap's license](https://github.com/twbs/bootstrap/blob/master/LICENSE) as `LICENSES/LicenseRef-MIT-Bootstrap.txt`.
2. Edit the header of the scss file to contain:

```
SPDX-FileCopyrightText: © 2019 Twitter, Inc.

SPDX-License-Identifier: LicenseRef-MIT-Bootstrap.txt
```

I don't see any additional troubles from a copyright and licensing perspective, but I can't green-light these things, so I'll defer to Matija :)

**Comment by silverhook** [comment]
> can someone please file an LRIT inbound licensing to discuss the proper way to bring this in?

You mean an Inbound Licensing ticket in the FOSS project of JIRA?

But, Carmen’s analysis is correct

**Comment by jbalsas** [comment]
> You mean an Inbound Licensing ticket in the FOSS project of JIRA?

Yeah, @silverhook, I wanted them to officially ping you in case you needed a breadcrumb trail 😉 

Since @carmenbianca already showed us the way, we can move forward with this.

Thanks both for your quick response!

**Comment by silverhook** [comment]
I’d appreciate if you guys still open up a ticket, so we do it diligently (please include a link to this issue as a reference).

But at a quick glance (and previous look at Bootstrap) this should be fine. If you are in a hurry, I’m 99% sure the end result will be the same as what Carmen wrote.

**Comment by pat270** [comment]
@jbalsas @silverhook @carmenbianca I created a FOSS ticket at https://issues.liferay.com/browse/FOSS-77.

Right now we are including Bootstrap's license at the top of https://github.com/liferay/clay/blob/master/packages/clay-css/src/scss/_bs4.scss#L3-L8 which looks like
bootstrap-attribution
in the final css file.

**Comment by silverhook** [comment]
Great, I’ll look into it in that issue. Ideally we should set it up so the copied snippet can be identified separately with its own copyright and license notice.

**Comment by pat270** [comment]
Thanks! Also does the license have to be in the final output or is it good enough to have it appear in the source?

**Comment by silverhook** [comment]
It does have to be in both, yes.

I do realise that especially with minifying JS and CSS this can get tricky. I have some ideas how to make it easy enough and not impacting the size of the minified version too much. But would like to discuss it with our frontend engineers to check for technical feasibility (although I’m fairly certain it should be no problem).

**Comment by pat270** [comment]
We have a lot of files with `@import 'atlas-variables';` that bring in Bootstrap's functions, variables, and mixins. If we add:
```
/*
    SPDX-FileCopyrightText: © 2019 Twitter, Inc.

    SPDX-License-Identifier: LicenseRef-MIT-Bootstrap
*/
```
at the top of `atlas-variables.scss`, it will place that comment at the top of each `main.scss`. This would add more than we would like. I think we concatenate these files at some point in production but not in development mode. @jbalsas the only option I can think of is stripping out duplicate attributions during concatenation. It would be nice if we could attribute just in the source and not have to output, but sounds like that would break the license agreement.

Here is my quick search of the files in Portal that import `atlas-variables.scss`:

```
apps/adaptive-media/adaptive-media-web/src/main/resources/META-INF/resources/adaptive_media/css/main.scss
apps/blogs/blogs-web/src/main/resources/META-INF/resources/blogs/css/main.scss
apps/calendar/calendar-web/src/main/resources/META-INF/resources/css/main.scss
apps/contacts/contacts-web/src/main/resources/META-INF/resources/css/main.scss
apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/css/ddm.scss
apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/css/document_library_preview.scss
apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/css/main.scss
apps/document-library/document-library-web/src/main/resources/META-INF/resources/image_gallery_display/css/main.scss
apps/dynamic-data-mapping/dynamic-data-mapping-form-renderer/src/main/resources/META-INF/resources/css/main.scss
apps/dynamic-data-mapping/dynamic-data-mapping-form-web/src/main/resources/META-INF/resources/admin/css/main.scss
apps/dynamic-data-mapping/dynamic-data-mapping-web/src/main/resources/META-INF/resources/css/main.scss
apps/fragment/fragment-web/src/main/resources/META-INF/resources/css/FragmentEditor.scss
apps/fragment/fragment-web/src/main/resources/META-INF/resources/css/FragmentNameEditor.scss
apps/fragment/fragment-web/src/main/resources/META-INF/resources/css/FragmentPreview.scss
apps/fragment/fragment-web/src/main/resources/META-INF/resources/css/SourceEditor.scss
apps/frontend-css/frontend-css-web/src/main/resources/META-INF/resources/main.scss
apps/frontend-css/frontend-css-web/src/main/resources/META-INF/resources/portal/_item_selector_preview.scss
apps/frontend-image-editor/frontend-image-editor-web/src/main/resources/META-INF/resources/ImageEditor.scss
apps/invitation/invitation-invite-members-web/src/main/resources/META-INF/resources/invite_members/css/main.scss
apps/journal/journal-web/src/main/resources/META-INF/resources/css/ddm_form.scss
apps/knowledge-base/knowledge-base-web/src/main/resources/META-INF/resources/admin/css/common.scss
apps/layout/layout-admin-web/src/main/resources/META-INF/resources/css/miller_columns/LayoutColumn.scss
apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/css/FragmentEntryLink.scss
apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/MasterLayout.scss
apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/PageEditor.scss
apps/layout/layout-seo-web/src/main/resources/META-INF/resources/css/main.scss
apps/login/login-web/src/main/resources/META-INF/resources/css/main.scss
apps/message-boards/message-boards-web/src/main/resources/META-INF/resources/message_boards/css/main.scss
apps/monitoring/monitoring-web/src/main/resources/META-INF/resources/css/main.scss
apps/portal-settings/portal-settings-web/src/main/resources/META-INF/resources/users_admin/css/main.scss
apps/portal-workflow/portal-workflow-task-web/src/main/resources/META-INF/resources/css/main.scss
apps/product-navigation/product-navigation-control-menu-theme-contributor/src/main/resources/META-INF/resources/product_navigation_control_menu.scss
apps/product-navigation/product-navigation-product-menu-theme-contributor/src/main/resources/META-INF/resources/product_navigation_product_menu.scss
apps/product-navigation/product-navigation-product-menu-web/src/main/resources/META-INF/resources/css/main.scss
apps/product-navigation/product-navigation-simulation-theme-contributor/src/main/resources/META-INF/resources/css/simulation_panel.scss
apps/questions/questions-web/src/main/resources/META-INF/resources/css/_question.scss
apps/questions/questions-web/src/main/resources/META-INF/resources/css/_questions.scss
apps/roles/roles-admin-web/src/main/resources/META-INF/resources/css/main.scss
apps/site-navigation/site-navigation-admin-web/src/main/resources/META-INF/resources/css/SiteNavigationMenuEditor.scss
apps/staging/staging-bar-web/src/main/resources/META-INF/resources/css/main.scss
apps/staging/staging-configuration-web/src/main/resources/META-INF/resources/css/main.scss
apps/subscription/subscription-web/src/main/resources/META-INF/resources/css/main.scss
apps/user-groups-admin/user-groups-admin-web/src/main/resources/META-INF/resources/css/main.scss
apps/users-admin/users-admin-web/src/main/resources/META-INF/resources/css/main.scss
apps/wiki/wiki-web/src/main/resources/META-INF/resources/wiki/css/main.scss
dxp/apps/segments/segments-experiment-web/src/main/resources/META-INF/resources/css/_click-goal.scss
sdk/gradle-plugins-css-builder/src/gradleTest/compileClayCssWithRuby/src/main/resources/css/main.scss
```

**Comment by jbalsas** [comment]
Hey @pat270, does the Sass compiler really embed those comments? I wouldn't expect so, I'd just expect it to make the variables and mixins available... but thinking about it, since it won't be able to distinguish css code from sass variables or mixins, it makes sense that it'll dump all other text... 🤔 

@silverhook offered to get on a call next week, to go over this, so we can probably use his help, but we need to understand the build process completely to make good use of that.

@bryceosterhaus, @matuzalemsteles, might be good to get some extra neurons in here 😉

**Comment by pat270** [comment]
It doesn't embed the comments right now.  Sass will dump `/* comment */` syntax to the final CSS. `// comment` doesn't output the comment during compilation.

**Comment by bryceosterhaus** [comment]
My only thought would be some post-processor that removes duplicate comment blocks

**Pull request merged**
