### PR TITLE
fix(clay-css): SVG Icons update the flag of Slovakia

### PR DESCRIPTION
**Pull request by pat270**
issue #2996

@bryceosterhaus @rolandpakai needs this for 7.2.x TS issue

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
LGTM!

**Comment by rolandpakai** [comment]
Hi @pat270 

when will be this changes released in a new clay-css version?

Thanks, Roland

**Comment by bryceosterhaus** [comment]
Hey @rolandpakai I am planning a release on March 26th. Will that be timely enough for you?

**Comment by rolandpakai** [comment]
Hi @pat270 

not really...
This is needed for a customer's request which is -21 days to the target resolve date... so we are in a big delay. 
Is it possible to release earlier?

Thanks, Roland

**Comment by pat270** [comment]
cc @bryceosterhaus

**Comment by bryceosterhaus** [comment]
@rolandpakai should be available in clay [v2.21.0 release](https://www.npmjs.com/package/clay-css/v/2.21.0)

**Comment by rolandpakai** [comment]
Thank you @bryceosterhaus

**Pull request merged**
