### PR TITLE
fix(@clayui/css): LPD-45052 Remove letter-spacing from diabled link i…

### PR DESCRIPTION
**Pull request by pat270**
…n menubar-primary

https://liferay.atlassian.net/browse/LPD-45052

### CODE REVIEW

**Comment by SelenaAungst** [comment]
Where in the clay site can I test this one? I am having trouble finding it

**Comment by SelenaAungst** [comment]
Ah ok I see its on storybook not the clay site- everything looks good to me.

**Review by ilzamcmed — APPROVED** [review]
LGTM!

**Pull request merged**
