### PR TITLE
Changes default tooltip position as Bottom to Top

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by julien** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by julien** [comment]
Hey @boton ,

I checked your pull request and everything looks fine.

Before merging it though, I'd like to know what @victorvalle, @marcoscv and @pat270 think about [this change](https://github.com/liferay/clay/issues/1082).

**Comment by pat270** [comment]
@julien, I agree with @boton. I like tooltips top by default better. It seems like the most common use case in portal.

**Comment by julien** [comment]
@pat270 thanks for the feedback!

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
