### PR TITLE
Create ClayTooltip component | Fixes #929

### LINKED ISSUE #929: Create ClayTooltip component
As a developer, I'd like to use tooltips in my applications using clay

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
LGTM but we need to find out what is happening with `Align`, is not working 100% fine.

**Comment by julien** [comment]
Thanks @carloslancha,

I guess we can go on with this and check what's going on with `Align` or look for an alternative.

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request merged**
