### PR TITLE
#600 Breaking Dropdown Action Togle and Quick Action Item require `.component-action`

### PR DESCRIPTION
**Pull request by pat270**

### CODE REVIEW

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jbalsas** [comment]
Hey @pat270, I think we need to hold off on breaking changes already. Could you explain what does this actually break or change so we can assess the impact before merging it in?

Thanks!

**Comment by pat270** [comment]
@jbalsas The thing that would break is the color of the dropdown action toggle and quick action item. The markup is essentially the same, just need to add the class `component-action` to `dropdown-toggle` or `quick-action-item`.

**Comment by carloslancha** [comment]
Hey @pat270 do we need to add component-action everywhere with `dropdown-toggle` and `quick-action-item`. I was in doubt because in your demo page of `dropdowns` is not added. Is this intended?

**Comment by pat270** [comment]
@carloslancha it's discretionary. In admin controls the markup is:
```
<div class="dropdown dropdown-action">
    <a class="component-action dropdown-toggle"></a>
</div>

<a class="component-action quick-action-item">
```

In Lexicon Sites:
```
<div class="dropdown dropdown-action">
    <a class="link-outline link-outline-borderless link-outline-primary dropdown-toggle"></a>
</div>
```
You can use button classes like `btn btn-primary` on `dropdown-toggle` as well.

**Comment by carloslancha** [comment]
@pat270 mmm, but that only applies to standalone dropdowns or also to components with dropdowns? I mean, a dropdown in a Card, in admin, will have `component-action` class but in a Lexicon Site it won't?

**Comment by pat270** [comment]
Card, List, Table has `component-action`. Quick Action Items in those also have `component-action`.

Asset Title Bar and Profile Info have the Sites version.
https://lexicondesign.io/docs/patterns/Sites/assetTitleBar.html
https://lexicondesign.io/docs/patterns/Sites/profileInfo.html

**Comment by carloslancha** [comment]
Understood @pat270 thx!

This implies that we need to change the components `clay-management-toolbar`, `clay-card`, `clay-table` and `clay-list` to pass as `triggerClasses` to ClayDropdown and to add to the `quick-action-item` the class `component-action`.

Could you take care of this @matuzalemsteles and resend over this pr?

Thx!

**Comment by matuzalemsteles** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by matuzalemsteles** [comment]
Forwarded #683

**Pull request closed without merging**
