### PR TITLE
feat(@clayui/css): Drilldown should work with Dropdown Menu, have dual click areas inside `dropdown-item`, and have `min-height`

### PR DESCRIPTION
**Pull request by pat270**
issue #3337 
@kresimir-coko You can view the markup and the pattern I used under Dropdowns Drilldown on the test site.

### CODE REVIEW

**Comment by bryceosterhaus** [comment]
@pat270 does drilldown work outside of dropdowns as well? I was looking through the examples and couldn't find anything specific for that

**Comment by pat270** [comment]
@bryceosterhaus yeah it works, just need to remove the dropdown classes and replace `<ul class="inline-scroller">` with the `<ul class="nav nav-stacked">` pattern. I didn't add an example because the requirements in https://issues.liferay.com/browse/LPS-114110 are vague, style and alignment will be off but it will work.

**Comment by bryceosterhaus** [comment]
@pat270 are you saying we can remove _all_ dropdown classes and have it work as intended? I took your example and removed all `dropdown-*` classes and I got something that looks like this

Screen Shot 2020-06-23 at 3 23 21 PM

**Comment by pat270** [comment]
Yeah that's working as intended for now. We can figure out how to style it with modifiers after we get more clarification about other use cases. I'm thinking we just swap out the `ul` block.

**Comment by kresimir-coko** [comment]
Hey @pat270 how can I access this version of your test site? I know the [one that's published](http://pat270.github.io/lexicon/v2.16.2/content/dropdowns-drill-down/), but idk how to access this one when the PR isn't merged to check how the markup looks in action.

**Comment by pat270** [comment]
@kresimir-coko  You can pull bryce's branch down:
1) `git remote add https://github.com/bryceosterhaus/clay.git bryce`
1) `git fetch bryce drilldown`
1) `cd clay/packages/clay-css`
1) `npm install` (needs node 10.x, I'm using 10.14.1)
1) `gulp serve`

**Comment by kresimir-coko** [comment]
@pat270 this PR has a couple conflicts, in case you missed it.

**Comment by pat270** [comment]
@kresimir-coko fixed conflicts

**Comment by bryceosterhaus** [comment]
@pat270 is this good to merge?

**Comment by pat270** [comment]
@bryceosterhaus yeah lets merge it

**Pull request merged**
