### PR TITLE
feat(@clayui/css): Absorb Bootstrap 4 mixins into Clay CSS

### PR DESCRIPTION
**Pull request by pat270**
issue #3149

### CODE REVIEW

**Comment by marcoscv-work** [comment]
LGTM

**Comment by matuzalemsteles** [comment]
@pat270 we were holding this until after the release, right? I think we can go ahead with it now. When the DXP release officially comes out, we can make a new release of Clay and see how it will behave.

**Comment by bryceosterhaus** [comment]
@pat270 any update on this PR? With 7.3 being released, are we good to merge this?

**Comment by pat270** [comment]
@bryceosterhaus I need to double check this one since it's been a while. I'll mark as ready when I do.

**Comment by pat270** [comment]
This one is ready.

**Pull request merged**
